In [1]:
import numpy as np
from pandas import read_csv    

import os
import glob
import time

from datetime import datetime


def XYZW(array):
    print(array)
    return str(array[0])+"\t"+str(array[1])+"\t"+str(array[2])+"\t"+str(array[3])
dir_path="./out/raw_cam2/land3D/"
out_path="./out/raw_cam2/unity-view/users/auro/"



files = glob.glob(out_path+"*")
for f in files:
    os.remove(f)
        
for path in os.listdir(dir_path):
    if os.path.isfile(os.path.join(dir_path, path)):
        series=read_csv(os.path.join(dir_path, path), sep="\t",parse_dates=True,header=None)
        data=np.array(series.values)
        print(series.values)
        
        head=np.mean(data[0:10], axis=0)
        print("head:",head)
        
        hand_left=np.mean(data[15:22:2], axis=0)
        print("hand_left:",hand_left)
        hand_right=np.mean(data[16:23:2], axis=0)
        print("hand_right:",hand_right)
        
        foot_left=np.mean(data[27:32:2], axis=0)
        print("foot_left:",foot_left)
        foot_right=np.mean(data[28:33:2], axis=0)
        print("foot_right:",foot_right)

        

        f = open(os.path.join(out_path, path), "w")
        f.write(XYZW(head)+"\n")
        f.write(XYZW(data[11])+"\n")
        f.write(XYZW(data[12])+"\n")
        f.write(XYZW(data[13])+"\n")
        f.write(XYZW(data[14])+"\n")
        f.write(XYZW(hand_right)+"\n")
        f.write(XYZW(hand_left)+"\n")
        f.write(XYZW(data[23])+"\n")
        f.write(XYZW(data[24])+"\n")
        f.write(XYZW(data[25])+"\n")
        f.write(XYZW(data[26])+"\n")        
        f.write(XYZW(foot_right)+"\n")
        f.write(XYZW(foot_left)+"\n")
        f.close()


[[ 0.04417851 -0.51557302 -0.41920307  0.99932933]
 [ 0.0642881  -0.544204   -0.40200669  0.99949479]
 [ 0.06545777 -0.54183155 -0.39038196  0.9991442 ]
 [ 0.06267154 -0.54394317 -0.3939904   0.99938667]
 [ 0.02777475 -0.54733932 -0.4113946   0.9996711 ]
 [ 0.03129194 -0.54740095 -0.42551002  0.99963582]
 [ 0.0337721  -0.53675616 -0.40309146  0.99973577]
 [ 0.15177138 -0.52350593 -0.264236    0.99899238]
 [-0.03639462 -0.47376212 -0.25808963  0.99874133]
 [ 0.08944909 -0.49761942 -0.36105415  0.99882764]
 [ 0.04452794 -0.46373996 -0.38683626  0.99851149]
 [ 0.23268925 -0.34749204 -0.1277844   0.99736828]
 [-0.07982067 -0.41101444 -0.0823013   0.99730092]
 [ 0.25970054 -0.13563746 -0.15537357  0.27130112]
 [-0.16251534 -0.13608743 -0.17816304  0.3972156 ]
 [ 0.23090808  0.01514397 -0.19074833  0.12786403]
 [-0.16145386 -0.07031294 -0.38273516  0.1731018 ]
 [ 0.22448756  0.02618416 -0.20002788  0.20926265]
 [-0.1335198  -0.06905121 -0.44317067  0.23903276]
 [ 0.20610212  0.01229127 -0.21

[[-0.00207562 -0.6570214  -0.29603747  0.99987364]
 [ 0.02226932 -0.6779446  -0.28265852  0.99964499]
 [ 0.02237115 -0.67709804 -0.27182892  0.99968338]
 [ 0.0216745  -0.67892873 -0.27353853  0.99968207]
 [-0.00415569 -0.68356401 -0.28696409  0.99973458]
 [-0.00361617 -0.68475962 -0.30015704  0.99980384]
 [ 0.0010283  -0.67019212 -0.28025338  0.99978465]
 [ 0.11068644 -0.66007996 -0.17880723  0.99988282]
 [-0.04853694 -0.61217219 -0.14300911  0.9996717 ]
 [ 0.04741947 -0.64083672 -0.24854727  0.99984431]
 [ 0.00371166 -0.60822856 -0.26422808  0.99974293]
 [ 0.21494618 -0.45619309 -0.08273642  0.99992967]
 [-0.08083965 -0.55145931  0.03683282  0.99959499]
 [ 0.33139697 -0.2606512  -0.09317654  0.99694604]
 [-0.13198356 -0.29310995 -0.02456623  0.88079834]
 [ 0.47795585 -0.03707056 -0.07911503  0.99131864]
 [-0.29000106 -0.19898245 -0.17709017  0.96317846]
 [ 0.51338214 -0.00363827 -0.07503708  0.98362839]
 [-0.31611657 -0.18897781 -0.21869299  0.96111655]
 [ 0.50315017  0.00814117 -0.10

[[ 0.05639907 -0.61438745 -0.32088032  0.9989506 ]
 [ 0.07191587 -0.6283192  -0.31119889  0.99730289]
 [ 0.0687677  -0.63138747 -0.30195412  0.99716043]
 [ 0.06771271 -0.63079256 -0.30170563  0.99749559]
 [ 0.04980819 -0.63902658 -0.32625815  0.99836797]
 [ 0.05000488 -0.63947409 -0.33749801  0.99851543]
 [ 0.05240942 -0.62251472 -0.31777179  0.99868661]
 [ 0.12496261 -0.61739326 -0.21294047  0.99876773]
 [-0.02367329 -0.57807219 -0.21110895  0.99822241]
 [ 0.08888843 -0.59406352 -0.27319136  0.99731833]
 [ 0.04581834 -0.56584132 -0.29910326  0.99723816]
 [ 0.2137841  -0.4991962  -0.1283977   0.99871945]
 [-0.08347224 -0.59385073 -0.02705156  0.99643433]
 [ 0.40738568 -0.62045825 -0.16901354  0.95390815]
 [-0.26276097 -0.68111509 -0.05768441  0.90602505]
 [ 0.45394737 -0.80317605 -0.18622133  0.92881495]
 [-0.40462726 -0.87856388 -0.11391053  0.95774907]
 [ 0.44967073 -0.86133915 -0.19379795  0.90642273]
 [-0.40952608 -0.93856651 -0.15849541  0.93845081]
 [ 0.4292849  -0.8900907  -0.20