In [1]:
import cv2
import os
import numpy as np
from PIL import Image
  
# importing library for plotting
from matplotlib import pyplot as plt

scene="test/scene5"

path0="./out/"+scene+"/raw_cam2/"
dir_path0=path0+'img/'
dir_path00=path0+'img3D/'
dir_path01=path0+'foot2D/'
dir_path000=path0+'faces/'
dir_path0000=path0+'land3D/'
times=[]
for path in os.listdir(dir_path0):
    # check if current path is a file
    if os.path.isfile(os.path.join(dir_path0, path)) and not '_' in path:
        times.append(path.replace('.jpg',''))
times.sort()
print(times)

['1687446214', '1687446215', '1687446216', '1687446217', '1687446218', '1687446219', '1687446220', '1687446221', '1687446222', '1687446223', '1687446224', '1687446225', '1687446226', '1687446227', '1687446228', '1687446229', '1687446230', '1687446231', '1687446232', '1687446233', '1687446234', '1687446235', '1687446236', '1687446237', '1687446238', '1687446239', '1687446240', '1687446241', '1687446242', '1687446243', '1687446244', '1687446245', '1687446246', '1687446247', '1687446248', '1687446249', '1687446250', '1687446254', '1687446255', '1687446256', '1687446257', '1687446258', '1687446259', '1687446260', '1687446261', '1687446262', '1687446263', '1687446264', '1687446265', '1687446266', '1687446267', '1687446268', '1687446269', '1687446270', '1687446271', '1687446272', '1687446273', '1687446274', '1687446275', '1687446276', '1687446277', '1687446278', '1687446279', '1687446280', '1687446281', '1687446282', '1687446283', '1687446284', '1687446285', '1687446286', '1687446287', '1687

In [2]:
from pandas import read_csv   
series=read_csv(path0+"tracking.txt", sep="\t",parse_dates=False)
tracking=series.values


print(tracking[:,1])

def getTracking(id0):
    ix=np.where(tracking[:,1] == id0)[0]
    if ix.size>0:
        return tracking[np.where(tracking[:,1] == id0)][0][2]
    return None

print(getTracking("1689846772_5"))


['1687446214_11' '1687446215_11' '1687446215_10' '1687446216_11'
 '1687446216_10' '1687446217_13' '1687446217_12' '1687446217_5'
 '1687446218_11' '1687446218_3' '1687446218_9' '1687446219_14'
 '1687446219_13' '1687446220_14' '1687446220_12' '1687446221_13'
 '1687446221_11' '1687446222_7' '1687446222_5' '1687446222_10'
 '1687446223_5' '1687446223_4' '1687446223_8' '1687446224_9'
 '1687446224_8' '1687446225_4' '1687446225_5' '1687446226_7'
 '1687446227_7' '1687446227_3' '1687446228_9' '1687446229_8'
 '1687446230_5' '1687446231_8' '1687446232_5' '1687446232_8'
 '1687446233_7' '1687446233_8' '1687446234_7' '1687446234_3'
 '1687446235_5' '1687446235_12' '1687446235_2' '1687446236_12'
 '1687446236_8' '1687446237_13' '1687446237_9' '1687446238_14'
 '1687446238_8' '1687446238_9' '1687446239_9' '1687446239_12'
 '1687446239_6' '1687446240_13' '1687446240_6' '1687446240_8'
 '1687446241_10' '1687446241_3' '1687446242_11' '1687446242_5'
 '1687446243_9' '1687446244_11' '1687446245_13' '1687446246_10

In [3]:
from pandas import read_csv   
series=read_csv(dir_path01+"tracking.txt", sep="\t",parse_dates=False)
foots=series.values


print(foots[:,1])

def getFoot(id0):
    ix=np.where(foots[:,0] == id0)[0]
    if ix.size>0:
        return foots[np.where(foots[:,0] == id0)][0][1:]
    return np.zeros(2)

print(getFoot("1689846s772_5"))

[0.92541856 1.2599589 1.4848865 0.9662584 0.9429025 1.2617953 1.4800589
 1.0455121 1.0193528 1.257006 1.481028 0.887937 0.8394713 0.9911939
 0.9563988 1.2535706 1.4781274 0.7009819 0.6757899 0.8676033 0.8230575
 1.2492001 1.480656 0.898718 0.8145427 1.2577019 1.4807552 0.90731996
 0.79749763 1.2523025 1.4822168 1.0337155 1.0025644 1.2482672 1.4761442
 1.129245 1.1080382 0.8769863 0.87533784 1.3228112 1.461999 0.8665529
 0.86268127 0.7499191 0.73000973 1.6513988 1.2770262 0.9414983 0.9268906
 1.6911387 1.2431304 0.8830377 0.865701 1.8844026 0.89830816 0.8943423
 0.8827734 0.89607936 0.85984915 0.8701725 0.84947217 0.8827236 0.86158204
 0.87730515 0.8623705 0.92518425 0.8990091 1.02036 0.9809445 0.9704354
 0.93047935 1.2178845 1.4135869 0.9849512 0.9700527 1.7829587 2.9472685
 0.8206462 0.80572754 1.2485356 1.7659044 0.9165237 0.8366264 0.93179363
 0.92548597 1.3473781 1.464233 1.0266914 1.0331964 1.3842394 1.4659215
 0.8240377 0.77230537 1.406666 1.4612627 1.0829573 1.0579151 0.5865349


In [4]:
from pandas import read_csv   
series=read_csv(dir_path000+"tracking.txt", sep="\t",parse_dates=False)
faces=series.values


print(faces[:,1])

def getFace(id0):
    ix=np.where(faces[:,0] == id0)[0]
    if ix.size>0:
        return faces[np.where(faces[:,0] == id0)][0][1]
    return None

print(getFace("1689846772_5"))


['aurora' 'aurora' 'aurora' 'aurora' 'aurora' 'aurora' 'aurora' 'aurora'
 'aurora' 'aurora' 'aurora' 'javi2' 'aurora' 'javi2' 'aurora' 'aurora'
 'aurora' 'aurora' 'javi2' 'javi2' 'aurora' 'aurora' 'javi2' 'javi2'
 'javi2' 'aurora' 'aurora' 'aurora' 'javi2' 'aurora' 'javi2' 'aurora'
 'aurora' 'aurora' 'aurora' 'javi2' 'aurora' 'javi2' 'aurora' 'aurora'
 'aurora' 'aurora' 'aurora' 'aurora' 'aurora' 'javi2' 'javi2' 'javi2'
 'javi2' 'javi2' 'javi2' 'javi2' 'javi2' 'aurora' 'javi2' 'javi2' 'javi2'
 'javi2']
None


In [5]:
from pandas import read_csv   



def get3D(id0):
    if os.path.isfile(os.path.join(dir_path0000, id0+".json")):
        series=read_csv(os.path.join(dir_path0000, id0+".json"), sep="\t",parse_dates=True,header=None)
        data=np.array(series.values)
        #print(series.values)
        
        head=np.mean(data[0:10], axis=0)
        #print("head:",head)
        
        hand_left=np.mean(data[15:22:2], axis=0)
        #print("hand_left:",hand_left)
        hand_right=np.mean(data[16:23:2], axis=0)
        #print("hand_right:",hand_right)
        
        foot_left=np.mean(data[27:32:2], axis=0)
        #print("foot_left:",foot_left)
        foot_right=np.mean(data[28:33:2], axis=0)
        #print("foot_right:",foot_right)

        
        ret=[head,data[11],data[12],data[13],data[14],hand_right,hand_left,data[23],data[24],data[25],data[26],foot_right,foot_left]
        return np.array(ret)
    else:
        return np.zeros((13,4)) 

print((get3D("1689846772_5")))


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [6]:
import glob


ffinal=open(path0+"fusion.tsv","w")
for t in times:
    jpgFilenamesList = glob.glob(dir_path00+t+"*.jpg")
    print(t)
    for f in jpgFilenamesList:
        id0=t+"_"+f[f.rfind("_")+len("_"):f.rfind(".")]
        body=(get3D(id0))
        loc2d=getFoot(id0)
        print("\t"+id0+"\t"+str(getTracking(id0))+"\t"+str(getFace(id0))+"\t"+str(body)+"\t"+str(loc2d[0])+"\t"+str(loc2d[1]))
        ffinal.write(str(t)+"\t"+str(id0)+"\t"+str(getTracking(id0))+"\t"+str(getFace(id0)))
        ffinal.write("\t"+str(loc2d[0]).replace('.',',')+"\t"+str(loc2d[1]).replace('.',','))
        for p in body.flatten():
                print(p)
                ffinal.write("\t"+str(p).replace('.',','))
        ffinal.write("\n")
ffinal.close()

1687446214
	1687446214_10	None	None	[[ 0.01564235 -0.56792632 -0.25202549  0.98953235]
 [ 0.19783655 -0.40976235 -0.02748821  0.99627042]
 [-0.12145012 -0.48216501  0.0027909   0.99579078]
 [ 0.2461767  -0.21733342 -0.12919752  0.63664871]
 [-0.1906005  -0.23108947 -0.13680577  0.30536008]
 [-0.09435067 -0.34981926 -0.3811851   0.74846299]
 [ 0.10358883 -0.31995495 -0.24574235  0.71561722]
 [ 0.10647102  0.00252062  0.0393417   0.066223  ]
 [-0.10345878 -0.01105119 -0.03865874  0.06927668]
 [ 0.08842711  0.38101935 -0.1025776   0.00152557]
 [-0.06187388  0.28607896 -0.19789237  0.00279431]
 [-0.12769439  0.6481245  -0.02371169  0.00116116]
 [ 0.05309201  0.68833071 -0.07781721  0.00177647]]	0.92541856	1.8222897
0.015642347512766698
-0.5679263174533844
-0.25202548801898955
0.989532345533371
0.197836548089981
-0.4097623527050018
-0.0274882111698389
0.9962704181671144
-0.1214501187205314
-0.4821650087833404
0.0027909001801162
0.9957907795906068
0.2461767047643661
-0.2173334211111068
-0.12

	1687446224_9	1	None	[[-0.26289931 -0.61811507 -0.19016647  0.99976667]
 [-0.08864027 -0.40946233 -0.24711035  0.99998474]
 [-0.04422911 -0.5562138   0.09208294  0.9998641 ]
 [-0.11681744 -0.17409873 -0.22406279  0.9471904 ]
 [-0.02558479 -0.29547828  0.18828113  0.00216232]
 [-0.24420284 -0.28719076  0.24025048  0.00503373]
 [-0.2505916  -0.20561843  0.0375535   0.64380778]
 [ 0.00844944  0.02472427 -0.0617752   0.99997425]
 [-0.00835757 -0.02965062  0.06179179  0.99996471]
 [ 0.1385905   0.38189825  0.10576574  0.93759751]
 [-0.11890329  0.25753778  0.1983147   0.62143224]
 [-0.32566581  0.64088964  0.32036526  0.8527146 ]
 [ 0.23075626  0.66626012  0.3351253   0.93770502]]	1.6911387	2.1434011
-0.26289930790662763
-0.6181150674819946
-0.19016646742820736
0.9997666716575623
-0.0886402651667594
-0.4094623327255249
-0.2471103519201278
0.9999847412109376
-0.0442291125655174
-0.5562137961387634
0.0920829400420188
0.999864101409912
-0.1168174445629119
-0.1740987300872802
-0.224062785506248

	1687446228_9	0	aurora	[[ 0.04055247 -0.56471671 -0.42034622  0.9910809 ]
 [ 0.19135363 -0.41725296 -0.15149999  0.99461645]
 [-0.11544009 -0.48160791 -0.13130094  0.99149537]
 [ 0.26878098 -0.22189596 -0.10559832  0.31781599]
 [-0.19992261 -0.21536207 -0.11423628  0.36011741]
 [-0.06601689 -0.12425108 -0.18495005  0.03845694]
 [ 0.22647658 -0.07921798 -0.07423069  0.02869673]
 [ 0.10403191  0.00551759  0.0415762   0.60384935]
 [-0.10116175 -0.01248311 -0.04193818  0.6630491 ]
 [ 0.08713833  0.38722163  0.0170748   0.03150912]
 [-0.06983513  0.28816977 -0.1235675   0.13133058]
 [-0.12351724  0.67087716  0.01690278  0.03421228]
 [ 0.08338595  0.73071468  0.16569807  0.01750578]]	0.8827236	1.8122467
0.04055247381329535
-0.5647167086601257
-0.42034622132778166
0.9910808980464936
0.1913536339998245
-0.4172529578208923
-0.1514999866485595
0.994616448879242
-0.1154400929808616
-0.4816079139709472
-0.1313009411096573
0.9914953708648682
0.2687809765338897
-0.2218959629535675
-0.105598323047161

1687446244
	1687446244_11	3	None	[[ 2.79644427e-01 -5.31935140e-01  5.47081532e-02  9.98207664e-01]
 [ 2.16471627e-02 -4.24719155e-01  1.53590903e-01  9.99909401e-01]
 [ 2.91885436e-01 -4.50002730e-01 -1.32230879e-03  9.99832153e-01]
 [ 1.14112951e-01 -3.44445169e-01  3.07417959e-01  3.38041270e-03]
 [ 4.29988623e-01 -2.83865094e-01  2.83487514e-02  3.27899605e-01]
 [ 5.69033608e-01 -4.62884881e-01  2.09916651e-01  7.97578916e-01]
 [ 2.41429094e-01 -4.51410905e-01  6.87262118e-01  7.54410680e-03]
 [-8.16935077e-02 -8.14799033e-03  9.76702794e-02  9.99929547e-01]
 [ 8.60122740e-02 -8.17447901e-04 -1.00179933e-01  9.99921799e-01]
 [ 8.50010067e-02  8.82793032e-03  3.15568149e-01  3.87147628e-02]
 [ 4.07795817e-01  6.06010780e-02  6.02234453e-02  6.79040790e-01]
 [ 5.32846302e-02  2.48956144e-01  1.45885500e-01  7.69158602e-01]
 [-1.17293758e-01  2.61065632e-01  2.91781813e-01  4.62541372e-01]]	1.440153	1.9274153
0.2796444267034531
-0.5319351404905319
0.05470815319567914
0.998207664489746

	1687446248_2	1	None	[[ 1.17726919e-01 -5.59012496e-01 -1.57898742e-01  9.94805700e-01]
 [ 1.77876443e-01 -4.12773401e-01  2.97716912e-02  9.99682307e-01]
 [-8.87550414e-02 -5.01757503e-01  1.36247948e-02  9.97817636e-01]
 [ 2.52210021e-01 -2.76989698e-01 -6.98870122e-02  9.35115218e-01]
 [-1.51728392e-01 -2.61254847e-01 -8.57659206e-02  5.53978026e-01]
 [-2.90004006e-02 -2.42707450e-01 -1.93885364e-01  3.37255716e-01]
 [ 2.34211456e-01 -4.21145990e-01 -1.87205866e-01  9.57271203e-01]
 [ 9.27353799e-02 -1.60405878e-04  4.95938174e-02  2.56270230e-01]
 [-8.78504664e-02 -6.27625408e-03 -4.98561822e-02  1.56609282e-01]
 [ 9.20255631e-02  3.96703571e-01 -5.55531904e-02  1.54249715e-02]
 [-1.93931330e-02  3.40761989e-01 -1.30463511e-01  1.20386053e-02]
 [-8.04416711e-02  7.74459958e-01  4.84345390e-02  3.86080022e-03]
 [ 7.90341944e-02  7.91264216e-01  2.76555572e-02  7.43297130e-03]]	1.005283	1.8523604
0.117726919054985
-0.559012496471405
-0.15789874196052547
0.9948056995868683
0.177876442

	1687446266_11	0	None	[[ 7.19698943e-02 -5.29422545e-01 -4.08540604e-01  9.89196038e-01]
 [ 1.72190487e-01 -3.91581535e-01 -1.73312470e-01  9.96951580e-01]
 [-1.24965861e-01 -4.65536445e-01 -1.58695519e-01  9.94033992e-01]
 [ 2.33916625e-01 -1.96793020e-01 -1.86609611e-01  4.88990694e-01]
 [-1.91358045e-01 -1.86342686e-01 -1.58156067e-01  5.06090641e-01]
 [-1.41348539e-01 -4.39472282e-02 -2.33488992e-01  5.00561912e-02]
 [ 1.38603957e-01 -9.00902767e-02 -2.27661960e-01  4.65407502e-02]
 [ 1.00031585e-01  3.85907455e-03  4.02712412e-02  6.12345338e-01]
 [-9.68189165e-02 -9.73923691e-03 -4.04090136e-02  6.64499462e-01]
 [ 9.20418948e-02  3.92024219e-01 -7.83403753e-04  1.44408671e-02]
 [-6.49842620e-02  3.09683442e-01 -9.45764109e-02  2.71372069e-02]
 [-1.25401763e-01  6.96627816e-01  6.61529601e-02  6.22944022e-03]
 [ 7.48538499e-02  7.37564921e-01  1.23202043e-01  5.23675745e-03]]	0.921739	1.823953
0.0719698943197727
-0.5294225454330445
-0.40854060351848603
0.9891960382461548
0.1721904

	1687446271_4	0	None	[[ 0.10088214 -0.5763013  -0.14568069  0.97448426]
 [ 0.16012195 -0.42855117  0.06168227  0.99435413]
 [-0.07506261 -0.49554685  0.01626003  0.98851341]
 [ 0.20293519 -0.29870743  0.00688091  0.21429273]
 [-0.14724606 -0.26146275 -0.09259296  0.21126722]
 [ 0.01335674 -0.28704971 -0.17472007  0.03855751]
 [ 0.16300398 -0.41607197 -0.03563803  0.13826331]
 [ 0.08380576 -0.002092    0.06067056  0.04003595]
 [-0.07907835 -0.00420604 -0.06092061  0.03876589]
 [ 0.0879978   0.39098367 -0.01876157  0.00188525]
 [-0.01073113  0.35399738 -0.19797425  0.00515678]
 [-0.08472227  0.77285288 -0.05434523  0.00150898]
 [ 0.10962141  0.76227542  0.06461265  0.00153188]]	1.0106993	1.8525838
0.10088213756680486
-0.5763013005256653
-0.14568068683147425
0.9744842648506165
0.1601219475269317
-0.4285511672496795
0.0616822727024555
0.9943541288375854
-0.0750626102089881
-0.4955468475818634
0.0162600316107273
0.9885134100914
0.2029351890087127
-0.2987074255943298
0.0068809082731604
0.214

	1687446289_12	3	None	[[ 0.03726026 -0.65999438  0.09109435  0.99933292]
 [-0.16012692 -0.44707847 -0.01934022  0.99993134]
 [ 0.21565685 -0.49395451  0.06010754  0.99989343]
 [-0.22836475 -0.24638228  0.06367574  0.74483889]
 [ 0.2869736  -0.18864869  0.10154556  0.72119039]
 [ 0.11299396 -0.21987091  0.26446585  0.01650135]
 [-0.09219448 -0.22839262  0.41359429  0.01224256]
 [-0.1033472   0.00524431  0.01318054  0.99983907]
 [ 0.10595508 -0.0117772  -0.01598159  0.99989295]
 [-0.17286682  0.36589149  0.15113115  0.99036294]
 [ 0.18458037  0.31716362  0.05185798  0.98276585]
 [ 0.18219664  0.74023157  0.14618016  0.9320033 ]
 [-0.18593091  0.67780761  0.27239761  0.95385812]]	0.66410345	1.7948282
0.0372602621093392
-0.659994375705719
0.09109435110003684
0.9993329167366027
-0.1601269245147705
-0.4470784664154053
-0.0193402208387851
0.9999313354492188
0.2156568467617035
-0.4939545094966888
0.0601075366139411
0.9998934268951416
-0.2283647507429123
-0.2463822811841964
0.0636757388710975
0

	1687446306_8	3	javi2	[[ 0.07748436 -0.58654671 -0.3531019   0.99847369]
 [ 0.13866171 -0.46339768 -0.08074266  0.99996519]
 [-0.13721852 -0.4854987  -0.17412566  0.99996221]
 [ 0.17712007 -0.24250217 -0.03409067  0.81161672]
 [-0.13269943 -0.16968134 -0.23983109  0.99197   ]
 [ 0.03449873 -0.01335118 -0.35899324  0.97956587]
 [ 0.11319918  0.0092098  -0.08114043  0.71202174]
 [ 0.09290539 -0.00506736  0.06958367  0.99992895]
 [-0.09147181  0.0021411  -0.06794625  0.99992549]
 [ 0.10569929  0.44318926  0.07177073  0.8358376 ]
 [-0.03954536  0.33112809 -0.18372107  0.93170863]
 [-0.08236931  0.67278989  0.08076943  0.59325717]
 [ 0.09494102  0.80479453  0.26862156  0.84081606]]	0.617143	1.7537048
0.07748435661196705
-0.5865467071533204
-0.35310189574956896
0.9984736919403077
0.1386617124080658
-0.4633976817131042
-0.0807426646351814
0.9999651908874512
-0.1372185200452804
-0.485498696565628
-0.1741256564855575
0.9999622106552124
0.1771200746297836
-0.2425021678209304
-0.0340906679630279


In [7]:
import pandas as pd

series=read_csv(path0+"fusion.tsv", sep="\t",decimal=",",parse_dates=False)
alldata=series.values
print(alldata)

users=np.unique(alldata[:,2])

print("users:",users)
for u in users:
    
    ix=np.where(alldata[:,2]==u)
    print(u)
    unique_elements, counts_elements = np.unique(alldata[ix,3], return_counts=True)
    print(unique_elements,counts_elements,unique_elements[np.argmax(counts_elements)])
    if(unique_elements[np.argmax(counts_elements)] == "None" ):
        counts_elements[np.argmax(counts_elements)]=0
        print("\t None",unique_elements,counts_elements,unique_elements[np.argmax(counts_elements)])
        print(unique_elements,counts_elements,unique_elements[np.argmax(counts_elements)])
        alldata[ix,3]=unique_elements[np.argmax(counts_elements)]      
        
    if(unique_elements[np.argmax(counts_elements)] != "None" ):
        alldata[ix,3]=unique_elements[np.argmax(counts_elements)]

ffinal=open(path0+"fusion2.tsv","w")
for x in alldata:
    for y in x:
        ffinal.write(str(y).replace('.',',')+"\t")
    ffinal.write("\n")
ffinal.close()        

[[1687446214 '1687446214_11' 1 ... 0.6751885016759237 0.466074138879776
  0.8926827112833658]
 [1687446215 '1687446215_10' 0 ... 0.7265299359957377 0.1496502012014388
  0.0030674715526401]
 [1687446215 '1687446215_11' 1 ... 0.6671377420425415 0.4627430339654286
  0.8940231601397196]
 ...
 [1687446307 '1687446307_7' 3 ... 0.7342182795206705 0.4954427778720855
  0.4559145073095957]
 [1687446308 '1687446308_5' 3 ... 0.8205834825833639 0.1226913928985595
  0.967499295870463]
 [1687446309 '1687446309_7' 3 ... 0.7233943939208984 0.2907314697901408
  0.8993943333625793]]
users: [0 1 2 3 4]
0
['None' 'aurora'] [34 22] None
	 None ['None' 'aurora'] [ 0 22] aurora
['None' 'aurora'] [ 0 22] aurora
1
['None' 'javi2'] [18  4] None
	 None ['None' 'javi2'] [0 4] javi2
['None' 'javi2'] [0 4] javi2
2
['None' 'aurora' 'javi2'] [24  9  3] None
	 None ['None' 'aurora' 'javi2'] [0 9 3] aurora
['None' 'aurora' 'javi2'] [0 9 3] aurora
3
['None' 'aurora' 'javi2'] [39  2 16] None
	 None ['None' 'aurora' 'javi2