In [1]:
import os


# cam1 to cam2
dir_cam1 = "cam2"
dir_cam2 = "floor"



In [2]:
import cv2
import numpy as np

sourcePoints=[]
targetPoints=[]

#cam1
sourcePoints.append((120,275))
targetPoints.append((0,3.5))

sourcePoints.append((205,210))
targetPoints.append((0,7))

sourcePoints.append((335,228))
targetPoints.append((3.5,7))

sourcePoints.append((488,247))
targetPoints.append((7,7))

sourcePoints.append((478,355))
targetPoints.append((7,3.5))

#cam2
sourcePoints=[]
targetPoints=[]

sourcePoints.append((532,248))
targetPoints.append((0,0))

sourcePoints.append((388,220))
targetPoints.append((3.5,0))

sourcePoints.append((258,192))
targetPoints.append((7,0))

sourcePoints.append((172,251))
targetPoints.append((7,3.5))

sourcePoints.append((47,335))
targetPoints.append((7,7))

sourcePoints.append((325,300))
targetPoints.append((3.5,3.5))

sourcePoints.append((518,351))
targetPoints.append((0,3.5))

#cam2
sourcePoints=[]
targetPoints=[]

sourcePoints.append((53,270))
targetPoints.append((0,2))

sourcePoints.append((121,305))
targetPoints.append((1.25,2))

sourcePoints.append((215,256))
targetPoints.append((1.25,1.25))

sourcePoints.append((420,320))
targetPoints.append((1.25,2.5))

sourcePoints.append((5,358))
targetPoints.append((1.25,3))

sourcePoints.append((168,350))
targetPoints.append((2.5,3.5))

sourcePoints.append((427,355))
targetPoints.append((3.25,2))


In [3]:
sourcePoints=np.array(sourcePoints)
targetPoints=np.array(targetPoints)
#calculamos homografia
H, mask = cv2.findHomography(sourcePoints, targetPoints, cv2.RANSAC)
print(H)

[[ 8.60759714e-04 -5.05073441e-05  9.43122963e-02]
 [ 3.89161859e-04 -4.03189660e-03  1.62029643e+00]
 [ 1.85077696e-04 -2.64351912e-03  1.00000000e+00]]


In [4]:
pts1 = sourcePoints.reshape(-1,1,2).astype(np.float32)
#Multiplicamos por H los origenes para saber donde caen y comparamos con la real
dst2 = cv2.perspectiveTransform(pts1, H)
for ix in range(0,len(dst2)):
    print(pts1[ix],"prediction ",dst2[ix][0], " real ", targetPoints[ix])

[[ 53. 270.]] prediction  [0.42658928 1.8655404 ]  real  [0. 2.]
[[121. 305.]] prediction  [0.84702283 2.0250528 ]  real  [1.25 2.  ]
[[215. 256.]] prediction  [0.73390764 1.8504316 ]  real  [1.25 1.25]
[[420. 320.]] prediction  [1.8967069 2.1290925]  real  [1.25 2.5 ]
[[  5. 358.]] prediction  [1.4764627 3.278421 ]  real  [1.25 3.  ]
[[168. 350.]] prediction  [2.0899255 2.5931256]  real  [2.5 3.5]
[[427. 355.]] prediction  [3.1578467 2.5263057]  real  [3.25 2.  ]


In [5]:

np.save("H"+dir_cam1+"x"+dir_cam2+".npy",H)
H2=np.load("H"+dir_cam1+"x"+dir_cam2+".npy")
print(H2)





[[ 8.60759714e-04 -5.05073441e-05  9.43122963e-02]
 [ 3.89161859e-04 -4.03189660e-03  1.62029643e+00]
 [ 1.85077696e-04 -2.64351912e-03  1.00000000e+00]]


In [6]:
sourcePoints=np.array([[[ 421,286]],[[ 111,267  ]],[[179,127]]])
pts1 = sourcePoints.reshape(-1,1,2).astype(np.float32)
#Multiplicamos por H los origenes para saber donde caen y comparamos con la real
dst2 = cv2.perspectiveTransform(pts1, H2)
for ix in range(0,len(dst2)):
    print(pts1[ix],"prediction ",dst2[ix][0])

[[421. 286.]] prediction  [1.3739874 1.9604459]
[[111. 267.]] prediction  [0.5603994 1.865053 ]
[[179. 127.]] prediction  [0.3469647 1.6889908]
