In [1]:
import os


# cam1 to cam2
dir_cam1 = "cam1"
dir_cam2 = "floor"



In [2]:
import cv2
import numpy as np

sourcePoints=[]
targetPoints=[]

sourcePoints.append((179,127))
targetPoints.append((1.5,1))

sourcePoints.append((400,156))
targetPoints.append((3,1))

sourcePoints.append((460,255))
targetPoints.append((4,2))

sourcePoints.append((500,358))
targetPoints.append((4,3))

sourcePoints.append((3,200))
targetPoints.append((0,3))

sourcePoints.append((175,260))
targetPoints.append((1.75,2))

sourcePoints.append((375,295))
targetPoints.append((3,2))

sourcePoints.append((300,360))
targetPoints.append((2,3))

In [3]:
sourcePoints=np.array(sourcePoints)
targetPoints=np.array(targetPoints)
#calculamos homografia
H, mask = cv2.findHomography(sourcePoints, targetPoints, cv2.RANSAC)
print(H)

[[ 7.99756141e-03  2.83420315e-04  8.01871804e-03]
 [-2.86452111e-03  1.03891556e-02  4.58987734e-01]
 [-1.56173238e-04  3.21011141e-04  1.00000000e+00]]


In [4]:
pts1 = sourcePoints.reshape(-1,1,2).astype(np.float32)
#Multiplicamos por H los origenes para saber donde caen y comparamos con la real
dst2 = cv2.perspectiveTransform(pts1, H)
for ix in range(0,len(dst2)):
    print(pts1[ix],"prediction ",dst2[ix][0], " real ", targetPoints[ix])

[[179. 127.]] prediction  [1.4569086 1.2496489]  real  [1.5 1. ]
[[400. 156.]] prediction  [3.2920506 0.9456051]  real  [3. 1.]
[[460. 255.]] prediction  [3.7218828 1.7727827]  real  [4. 2.]
[[500. 358.]] prediction  [3.9623108 2.6484869]  real  [4. 3.]
[[  3. 200.]] prediction  [0.08338127 2.3767464 ]  real  [0. 3.]
[[175. 260.]] prediction  [1.4025524 2.5175598]  real  [1.75 2.  ]
[[375. 295.]] prediction  [2.9829302 2.364168 ]  real  [3. 2.]
[[300. 360.]] prediction  [2.3479836 3.1250021]  real  [2. 3.]


In [5]:

np.save("H"+dir_cam1+"x"+dir_cam2+".npy",H)
H2=np.load("H"+dir_cam1+"x"+dir_cam2+".npy")
print(H2)





[[ 7.99756141e-03  2.83420315e-04  8.01871804e-03]
 [-2.86452111e-03  1.03891556e-02  4.58987734e-01]
 [-1.56173238e-04  3.21011141e-04  1.00000000e+00]]


In [6]:
sourcePoints=np.array([[[ 421,286]],[[ 111,267  ]],[[179,127]]])
pts1 = sourcePoints.reshape(-1,1,2).astype(np.float32)
#Multiplicamos por H los origenes para saber donde caen y comparamos con la real
dst2 = cv2.perspectiveTransform(pts1, H2)
for ix in range(0,len(dst2)):
    print(pts1[ix],"prediction ",dst2[ix][0])

[[421. 286.]] prediction  [3.3682723 2.1678286]
[[111. 267.]] prediction  [0.90925145 2.7283783 ]
[[179. 127.]] prediction  [1.4569086 1.2496489]
