In [1]:
#! git clone https://github.com/WongKinYiu/yolov7.git
#!pip install torchvision
#!pip install toch
#!pip install yoloface

In [2]:
import argparse
import time
from pathlib import Path

import numpy as np



import os
import glob
import cv2
import torch
import torch.backends.cudnn as cudnn
from numpy import random

from yoloface import face_analysis

from models.experimental import attempt_load
from utils.datasets import LoadStreams, LoadImages
from utils.general import check_img_size, check_requirements, check_imshow, non_max_suppression, apply_classifier, \
    scale_coords, xyxy2xywh, strip_optimizer, set_logging, increment_path
from utils.plots import plot_one_box
from utils.torch_utils import select_device, load_classifier, time_synchronized, TracedModel

import mediapipe as mp
mp_drawing = mp.solutions.drawing_utils
mp_drawing_styles = mp.solutions.drawing_styles
mp_pose = mp.solutions.pose

BG_COLOR = (192, 192, 192)

print("HOLA")

dir_cam1 = "cam1"
dir_cam2 = "floor"

H2=np.load("H"+dir_cam1+"x"+dir_cam2+".npy")


def detect(save_img=True):
    
    files = glob.glob("./out/img/*")
    for f in files:
        os.remove(f)

    files = glob.glob("./out/img3D/*")
    for f in files:
        os.remove(f)
        
    files = glob.glob("./out/labels/*")
    for f in files:
        os.remove(f)        
    
    files = glob.glob("./out/foot2D/*")
    for f in files:
        os.remove(f)    
        
    files = glob.glob("./out/land3D/*")
    for f in files:
        os.remove(f) 
        
    files = glob.glob("./out/faces/*")
    for f in files:
        os.remove(f)
        
    augment=False
    conf_thres=0.25
    iou_thres=0.45
    classes=None
    agnostic_nms=False
    save_conf=True
    save_txt=True
    source='rtsp://Adetem:AuroraJavi@192.168.95.146:554/stream2'
    source='rtsp://Adetem:AuroraJavi@192.168.95.66:554/stream2'
    #source='0'
    #source, weights, view_img, save_txt, imgsz, trace = opt.source, opt.weights, opt.view_img, opt.save_txt, opt.img_size, not opt.no_trace
    #save_img = not opt.nosave and not source.endswith('.txt')  # save inference images
    #webcam = source.isnumeric() or source.endswith('.txt') or source.lower().startswith(
    #    ('rtsp://', 'rtmp://', 'http://', 'https://'))
    imgsz=480
    webcam=True
    project="."
    name="out"
    exist_ok=True
    
    # Directories
    #save_dir = Path(increment_path(Path(opt.project) / opt.name, exist_ok=opt.exist_ok))  # increment run
    #(save_dir / 'labels' if save_txt else save_dir).mkdir(parents=True, exist_ok=True)  # make dir
 
    save_dir = Path(increment_path(Path(project) / name, exist_ok=exist_ok))  # increment run
    (save_dir / 'labels' if save_txt else save_dir).mkdir(parents=True, exist_ok=True)  # make dir
    
    
    pose=mp_pose.Pose(  static_image_mode=True,model_complexity=2,enable_segmentation=True,min_detection_confidence=0.5)
    
    face=face_analysis()
    
    # Initialize
    #set_logging()
    device = select_device('')
    #half = device.type != 'cpu'  # half precision only supported on CUDA
    half = False
    # Load model
    model = attempt_load('yolov7.pt', map_location=device)  # load FP32 model
    stride = int(model.stride.max())  # model stride
    imgsz = check_img_size(imgsz, s=stride)  # check img_size

    #if trace:
    #model = TracedModel(model, device, opt.img_size)

    #if half:
    #    model.half()  # to FP16

    # Second-stage classifier
    classify = False
    if classify:
        modelc = load_classifier(name='resnet101', n=2)  # initialize
        modelc.load_state_dict(torch.load('weights/resnet101.pt', map_location=device)['model']).to(device).eval()

    # Set Dataloader
    #vid_path, vid_writer = None, None
    #if webcam:
    view_img = check_imshow()
    cudnn.benchmark = True  # set True to speed up constant image size inference
    dataset = LoadStreams(source, img_size=imgsz, stride=stride)
    #else:
    #    dataset = LoadImages(source, img_size=imgsz, stride=stride)

    # Get names and colors
    names = model.module.names if hasattr(model, 'module') else model.names
    colors = [[random.randint(0, 255) for _ in range(3)] for _ in names]

    # Run inference
    if device.type != 'cpu':
        model(torch.zeros(1, 3, imgsz, imgsz).to(device).type_as(next(model.parameters())))  # run once
    old_img_w = old_img_h = imgsz
    old_img_b = 1

    t0 = time.time()
    lastT=t0
    for path, img, im0s, vid_cap in dataset:
        try:
            
            ts = time.time()
            print("TIMELINE:",ts,lastT)
            #if(ts-lastT<3):
            #   continue
            lastT=ts
            print("I)img#",len(img),"im0s#",len(im0s))
            #img=[img[0]]
            #im0s=[im0s[0]]
            print("II)img#",len(img),"im0s#",len(im0s))
            img = torch.from_numpy(img).to(device)
            #print(img)
            img = img.half() if half else img.float()  # uint8 to fp16/32
            img /= 255.0  # 0 - 255 to 0.0 - 1.0
            if img.ndimension() == 3:
                img = img.unsqueeze(0)

            # Inference
            t1 = time_synchronized()
            with torch.no_grad():   # Calculating gradients would cause a GPU memory leak
                pred = model(img, augment=augment)[0]
            t2 = time_synchronized()

            # Apply NMS
            pred = non_max_suppression(pred, conf_thres, iou_thres, classes=classes, agnostic=agnostic_nms)
            t3 = time_synchronized()

            # Apply Classifier
            if classify:
                pred = apply_classifier(pred, modelc, img, im0s)

          
            # Process detections
            for i, det in enumerate(pred):  # detections per image
                print("pred i",i, det)
                p, s, im0, frame = path[i], '%g: ' % i, im0s[i].copy(), dataset.count
                
                p = Path(p)  # to Path
                save_path = str(save_dir / p.name)  # img.jpg
                print('save_path:',save_path)
                txt_path = str(save_dir / 'labels' / str(ts)) + ('' if dataset.mode == 'image' else f'_{frame}')  # img.txt
                gn = torch.tensor(im0.shape)[[1, 0, 1, 0]]  # normalization gain whwh
                if len(det):
                    # Rescale boxes from img_size to im0 size
                    det[:, :4] = scale_coords(img.shape[2:], det[:, :4], im0.shape).round()

                    # Print results
                    for c in det[:, -1].unique():
                        n = (det[:, -1] == c).sum()  # detections per class
                        s += f"{n} {names[int(c)]}{'s' * (n > 1)}, "  # add to string

                    # Write results
                    indexP=0
                    for *xyxy, conf, cls in reversed(det):
                        indexP=indexP+1
                        if save_txt:  # Write to file
                            x1,x2,y1,y2=int(xyxy[0].item()),int(xyxy[2].item()),int(xyxy[1].item()),int(xyxy[3].item())
                            print("x1:",x1,"x2:",x2,"y1:",y1,"y2:",y2)
                            xywh = (xyxy2xywh(torch.tensor(xyxy).view(1, 4)) / gn).view(-1).tolist()  # normalized xywh
                            line = (cls, *xywh, conf)
                            im00 = im0s[i][y1:y2, x1:x2]
                            img_path = str(save_dir / 'img' / str(ts)) + (f'_{frame}')  # img.txt
                            img_path=img_path+"_"+str(indexP)+"_"+names[int(cls)]
                            print(f" \t The image with the result is saved ?: {img_path}")
                            cv2.imwrite(img_path+ '.jpg', im00)
                    
                            with open(txt_path + '.txt', 'a') as f:
                                f.write(('%g ' * len(line)).rstrip() % line + '\n')
                                
                                
                            #head
                            if(cls==0):
                                try:
                                    box2,conf2=[],[]
                                    img2,box2,conf2=face.face_detection(frame_arr=im00,model='tiny')
                                    for iface,facebox in enumerate(box2):
                                        print("Box face:",facebox)
                                        im000 = im00[facebox[1]:facebox[1]+facebox[2], facebox[0]:facebox[0]+facebox[3]]
                                        img_path = str(save_dir / 'faces' / str(ts)) + (f'_{frame}')  # img.txt
                                        img_path=img_path+"_"+str(indexP)+"_"+names[int(cls)]+"_"+ str(iface)
                                        print(f" \t The face with the result is saved ?: {img_path}")
                                        cv2.imwrite(img_path+ '.jpg', im000)

                                except Exception as e:
                                    print("Bad ?",e)
                                    
                            #Pose 2D    
                            if(cls ==0):
                                results = pose.process(cv2.cvtColor(im00, cv2.COLOR_BGR2RGB))
                                image_height, image_width, _ = im00.shape
                                image_height0, image_width0, _ = im0.shape
                                
                                if not results.pose_landmarks:
                                     print("None 3D ")
                                else:
                                    print(
                                        f'Nose coordinates: ('
                                        f'{results.pose_landmarks.landmark[mp_pose.PoseLandmark.NOSE].x * image_width}, '
                                        f'{results.pose_landmarks.landmark[mp_pose.PoseLandmark.NOSE].y * image_height})'
                                    )
                                    print(
                                        f'Foot Left coordinates: ('
                                        f'{results.pose_landmarks.landmark[mp_pose.PoseLandmark.LEFT_FOOT_INDEX].x * image_width}, '
                                        f'{results.pose_landmarks.landmark[mp_pose.PoseLandmark.LEFT_FOOT_INDEX].y * image_height})'
                                    )
                                    print(
                                        f'Foot Right coordinates: ('
                                        f'{results.pose_landmarks.landmark[mp_pose.PoseLandmark.RIGHT_FOOT_INDEX].x * image_width}, '
                                        f'{results.pose_landmarks.landmark[mp_pose.PoseLandmark.RIGHT_FOOT_INDEX].y * image_height})'
                                    )
                                    
                                    
                                    
                                    #Foot location x 2D 
                                    sourcePoints=np.array([
                                            [[ results.pose_landmarks.landmark[mp_pose.PoseLandmark.LEFT_FOOT_INDEX].x * image_width0,
                                             results.pose_landmarks.landmark[mp_pose.PoseLandmark.LEFT_FOOT_INDEX].y * image_height0]],
                                            [[ results.pose_landmarks.landmark[mp_pose.PoseLandmark.RIGHT_FOOT_INDEX].x * image_width0,
                                             results.pose_landmarks.landmark[mp_pose.PoseLandmark.RIGHT_FOOT_INDEX].y * image_height0]]
                                        ])
                                    pts1 = sourcePoints.reshape(-1,1,2).astype(np.float32)
                                    #Multiplicamos por H los origenes para saber donde caen y comparamos con la real
                                    dst2 = cv2.perspectiveTransform(pts1, H2)
                                    img_path = str(save_dir / 'foot2D' / str(ts)) + (f'_{indexP}')  # img.txt
                                    f_land = open(img_path+".json", "w")

                                    # Plot 2D points
                                    img2D = np.zeros((im0.shape[0], im0.shape[1], 3), dtype=np.uint8)
                                    
                                    
    
                                    for ix in range(0,len(dst2)):
                                        print(pts1[ix],"prediction ",dst2[ix][0])
                                        f_land.write(str(dst2[ix][0][0])+"\t"+str(dst2[ix][0][1])+"\n")
                                        center=(int(dst2[ix][0][0]*100),int(dst2[ix][0][1]*100))
                                        print("center",center)
                                        img2D = cv2.circle(img2D, center , 2, 255, -1)
                        
                                    f_land.close()
                                    
                                    annotated_image = im00.copy()
                                    # Draw segmentation on the image.
                                    # To improve segmentation around boundaries, consider applying a joint
                                    # bilateral filter to "results.segmentation_mask" with "image".
                                    condition = np.stack((results.segmentation_mask,) * 3, axis=-1) > 0.1
                                    bg_image = np.zeros(im00.shape, dtype=np.uint8)
                                    bg_image[:] = BG_COLOR
                                    annotated_image = np.where(condition, annotated_image, bg_image)
                                    print(" 3D A")
                                    # Draw pose landmarks on the image.
                                    mp_drawing.draw_landmarks(
                                        annotated_image,
                                        results.pose_landmarks,
                                        mp_pose.POSE_CONNECTIONS,
                                        landmark_drawing_spec=mp_drawing_styles.get_default_pose_landmarks_style())
                                    print(" 3D B")
                                    img_path = str(save_dir / 'img3D' / str(ts)) + (f'_{indexP}')  # img.txt
                                    #img_path=img_path+"_"+str(i)+"_"+names[int(cls)]
                                    print(f" \t The image with the result is saved ?: {img_path}")
                                    cv2.imwrite(img_path+ '.jpg', annotated_image)

                                    print(" 3D C")
                                    img_path = str(save_dir / 'land3D' / str(ts)) + (f'_{indexP}')  # img.txt
                                    f_land = open(img_path+".json", "w")
                                    for land in results.pose_world_landmarks.landmark:
                                        #print("\t land:",land.x)
                                        f_land.write(str(land.x)+"\t"+str(land.y)+"\t"+str(land.z)+"\t"+str(land.visibility)+"\n")
                                    f_land.close()
                                    

                                
                        print("Saving all!")
                        if save_img or view_img:  # Add bbox to image
                            label = f'{names[int(cls)]} {conf:.2f}'
                            plot_one_box(xyxy, im0, label=label, color=colors[int(cls)], line_thickness=1)

                # Print time (inference + NMS)
                #print(f'{s}Done. ({(1E3 * (t2 - t1)):.1f}ms) Inference, ({(1E3 * (t3 - t2)):.1f}ms) NMS')

                # Stream results
                if view_img:
                    print("SHAPES:",im0.shape,img2D.shape)
                    hor = np.concatenate((im0, img2D), axis=1)
                    cv2.imshow(str(p), hor)
                    cv2.waitKey(1)  # 1 millisecond

                # Save results (image with detections)
                if save_img:
                    img_path = str(save_dir / 'img' / str(ts)) + ('' if dataset.mode == 'image' else f'_{frame}')  # img.txt
                
                    print(f" The image with the result is saved ?: {img_path}")
                    cv2.imwrite(img_path+ '.jpg', im0)
        except Exception as e:
            print(e)

    if save_txt or save_img:
        s = f"\n{len(list(save_dir.glob('labels/*.txt')))} labels saved to {save_dir / 'labels'}" if save_txt else ''
        #print(f"Results saved to {save_dir}{s}")

    print(f'Done. ({time.time() - t0:.3f}s)')


if __name__ == '__main__':
    print("hola")
    parser = argparse.ArgumentParser()
    parser.add_argument('--weights', nargs='+', type=str, default='yolov7.pt', help='model.pt path(s)')
    parser.add_argument('--source', type=str, default='inference/images', help='source')  # file/folder, 0 for webcam
    parser.add_argument('--img-size', type=int, default=640, help='inference size (pixels)')
    parser.add_argument('--conf-thres', type=float, default=0.25, help='object confidence threshold')
    parser.add_argument('--iou-thres', type=float, default=0.45, help='IOU threshold for NMS')
    parser.add_argument('--device', default='', help='cuda device, i.e. 0 or 0,1,2,3 or cpu')
    parser.add_argument('--view-img', action='store_true', help='display results')
    parser.add_argument('--save-txt', action='store_true', help='save results to *.txt')
    parser.add_argument('--save-conf', action='store_true', help='save confidences in --save-txt labels')
    parser.add_argument('--nosave', action='store_true', help='do not save images/videos')
    parser.add_argument('--classes', nargs='+', type=int, help='filter by class: --class 0, or --class 0 2 3')
    parser.add_argument('--agnostic-nms', action='store_true', help='class-agnostic NMS')
    parser.add_argument('--augment', action='store_true', help='augmented inference')
    parser.add_argument('--update', action='store_true', help='update all models')
    parser.add_argument('--project', default='runs/detect', help='save results to project/name')
    parser.add_argument('--name', default='exp', help='save results to project/name')
    parser.add_argument('--exist-ok', action='store_true', help='existing project/name ok, do not increment')
    parser.add_argument('--no-trace', action='store_true', help='don`t trace model')
    print("hola")
    #opt = parser.parse_args()
    #print(opt)
    print("hola")
    #check_requirements(exclude=('pycocotools', 'thop'))

    with torch.no_grad():
        print("hola")
        #if opt.update:  # update all models (to fix SourceChangeWarning)
        #    for opt.weights in ['yolov7.pt']:
        #        detect()
        #        strip_optimizer(opt.weights)
        #else:
        detect()


HOLA
hola
hola
hola
hola
yolov3-tiny_face.weights:: status : file already exists
yolov3_tiny_face.cfg:: status : file already exists
face_detection.weights:: status : file already exists
face_detection.cfg:: status : file already exists
Fusing layers... 
RepConv.fuse_repvgg_block
RepConv.fuse_repvgg_block
RepConv.fuse_repvgg_block
1/1: rtsp://Adetem:AuroraJavi@192.168.95.66:554/stream2...  success (640x360 at 15.00 FPS).

TIMELINE: 1687092859.4806216 1687092859.4646246
I)img# 1 im0s# 1
II)img# 1 im0s# 1


C:\Users\javie\anaconda3\lib\site-packages\torch\functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\TensorShape.cpp:3484.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]


pred i 0 tensor([[2.04084e+02, 5.06413e+01, 3.56592e+02, 2.61009e+02, 9.28108e-01, 0.00000e+00],
        [1.22080e+02, 8.95554e+00, 1.84400e+02, 1.25854e+02, 8.39233e-01, 0.00000e+00],
        [1.57304e+02, 8.40796e+00, 3.08509e+02, 9.42467e+01, 7.33223e-01, 5.70000e+01],
        [1.70633e+02, 9.19460e+01, 2.13656e+02, 1.36767e+02, 4.98845e-01, 2.60000e+01],
        [6.12900e-01, 1.01433e+01, 1.27918e+02, 1.70378e+02, 4.88071e-01, 5.70000e+01],
        [1.23615e+01, 2.44994e+01, 7.60562e+01, 9.97511e+01, 4.31475e-01, 2.60000e+01],
        [1.70964e+02, 9.19662e+01, 2.13906e+02, 1.36258e+02, 3.88523e-01, 2.40000e+01],
        [1.92866e+02, 1.41871e+02, 2.63349e+02, 1.64754e+02, 2.98457e-01, 6.50000e+01],
        [8.19928e+01, 4.12834e+01, 1.18783e+02, 6.74504e+01, 2.88927e-01, 7.30000e+01]])
save_path: out\stream2
x1: 109 x2: 158 y1: 43 y2: 78
 	 The image with the result is saved ?: out\img\1687092859.4806216_0_1_book
Saving all!
x1: 257 x2: 351 y1: 177 y2: 208
 	 The image with the re

pred i 0 tensor([[2.16078e+02, 7.22488e+01, 4.23825e+02, 2.73719e+02, 9.62578e-01, 0.00000e+00],
        [2.79214e+02, 7.65470e+01, 3.41346e+02, 1.61350e+02, 9.39634e-01, 6.30000e+01],
        [1.22438e+02, 9.17626e+00, 1.84534e+02, 1.12217e+02, 7.96858e-01, 0.00000e+00],
        [7.39555e-01, 9.64104e+00, 1.29434e+02, 1.70233e+02, 6.30962e-01, 5.70000e+01],
        [1.56191e+02, 8.42947e+00, 3.07853e+02, 9.89978e+01, 6.01426e-01, 5.70000e+01],
        [1.70421e+02, 9.19382e+01, 2.13854e+02, 1.36675e+02, 3.78528e-01, 2.60000e+01],
        [1.14805e+01, 2.45258e+01, 7.59820e+01, 1.00096e+02, 3.41969e-01, 2.60000e+01],
        [8.19398e+01, 4.13189e+01, 1.19180e+02, 6.70870e+01, 3.24325e-01, 7.30000e+01],
        [1.70499e+02, 9.22701e+01, 2.14046e+02, 1.36132e+02, 2.97365e-01, 2.40000e+01]])
save_path: out\stream2
x1: 227 x2: 285 y1: 111 y2: 170
 	 The image with the result is saved ?: out\img\1687092863.183989_3_1_backpack
Saving all!
x1: 109 x2: 159 y1: 43 y2: 77
 	 The image with the

Nose coordinates: (217.46086084842682, 40.29968082904816)
Foot Left coordinates: (6.249149411916733, 234.1366982460022)
Foot Right coordinates: (19.1166370511055, 229.53299760818481)
[[      14.65      312.18]] prediction  [    0.19461      3.3339]
center (19, 333)
[[     44.816      306.04]] prediction  [    0.41528      3.2166]
center (41, 321)
 3D A
 3D B
 	 The image with the result is saved ?: out\img3D\1687092865.066954_10
 3D C
Saving all!
SHAPES: (360, 640, 3) (360, 640, 3)
 The image with the result is saved ?: out\img\1687092865.066954_5
TIMELINE: 1687092866.0324996 1687092865.066954
I)img# 1 im0s# 1
II)img# 1 im0s# 1
pred i 0 tensor([[2.15749e+02, 7.00007e+01, 4.21206e+02, 2.73687e+02, 9.66797e-01, 0.00000e+00],
        [2.76900e+02, 7.46567e+01, 3.37630e+02, 1.60849e+02, 9.43394e-01, 6.30000e+01],
        [1.22048e+02, 9.27092e+00, 1.84486e+02, 1.06697e+02, 8.40825e-01, 0.00000e+00],
        [1.55331e+02, 8.79311e+00, 3.06503e+02, 1.00976e+02, 6.19180e-01, 5.70000e+01],
   

Nose coordinates: (236.6710603237152, 44.58716344833374)
Foot Left coordinates: (4.317373316735029, 256.04723489284515)
Foot Right coordinates: (32.3838472366333, 243.84169256687164)
[[     9.2104      332.77]] prediction  [    0.15921       3.519]
center (15, 351)
[[     69.086      316.91]] prediction  [    0.59614      3.2573]
center (59, 325)
 3D A
 3D B
 	 The image with the result is saved ?: out\img3D\1687092867.8617284_10
 3D C
Saving all!
SHAPES: (360, 640, 3) (360, 640, 3)
 The image with the result is saved ?: out\img\1687092867.8617284_8
TIMELINE: 1687092868.7422607 1687092867.8617284
I)img# 1 im0s# 1
II)img# 1 im0s# 1
pred i 0 tensor([[1.92244e+02, 6.56762e+01, 4.11261e+02, 2.72606e+02, 9.52809e-01, 0.00000e+00],
        [1.22609e+02, 9.05251e+00, 1.84406e+02, 1.23955e+02, 7.59215e-01, 0.00000e+00],
        [2.51849e+02, 1.19382e+02, 3.25559e+02, 1.93226e+02, 7.40654e-01, 6.30000e+01],
        [1.56023e+02, 8.35543e+00, 3.11683e+02, 1.09375e+02, 5.35561e-01, 5.70000e+01],


Box face: [204, 6, 82, 69]
 	 The face with the result is saved ?: out\faces\1687092870.5746148_11_10_person_0
Nose coordinates: (216.52788090705872, 60.620059847831726)
Foot Left coordinates: (4.184886038303375, 309.38135147094727)
Foot Right coordinates: (34.89531387388706, 200.57047033309937)
[[     8.9877      343.76]] prediction  [     0.1599      3.6112]
center (15, 361)
[[     74.943      222.86]] prediction  [    0.63268      2.4151]
center (63, 241)
 3D A
 3D B
 	 The image with the result is saved ?: out\img3D\1687092870.5746148_10
 3D C
Saving all!
SHAPES: (360, 640, 3) (360, 640, 3)
 The image with the result is saved ?: out\img\1687092870.5746148_11
TIMELINE: 1687092871.4647567 1687092870.5746148
I)img# 1 im0s# 1
II)img# 1 im0s# 1
pred i 0 tensor([[109.86052,  27.31298, 337.73901, 276.63483,   0.95779,   0.00000],
        [132.12282,  66.78989, 245.03169, 195.14240,   0.85773,  63.00000],
        [118.93989,   9.19330, 185.04742,  98.29935,   0.71539,   0.00000],
        [

 The image with the result is saved ?: out\img\1687092874.0573401_15
TIMELINE: 1687092874.7793007 1687092874.0573401
I)img# 1 im0s# 1
II)img# 1 im0s# 1
pred i 0 tensor([[6.21838e+01, 9.08409e+00, 2.24399e+02, 2.73326e+02, 9.19823e-01, 0.00000e+00],
        [1.59416e-01, 2.07605e+01, 1.27603e+02, 1.63747e+02, 9.12461e-01, 6.30000e+01],
        [2.08106e+02, 9.25011e+00, 3.08572e+02, 1.03028e+02, 3.82712e-01, 6.20000e+01],
        [2.08276e+02, 8.55128e+00, 3.74169e+02, 1.27360e+02, 3.38924e-01, 5.60000e+01],
        [3.04349e+02, 1.15007e+02, 3.85734e+02, 1.94704e+02, 2.74907e-01, 5.60000e+01]])
save_path: out\stream2
x1: 406 x2: 514 y1: 141 y2: 248
 	 The image with the result is saved ?: out\img\1687092874.7793007_16_1_chair
Saving all!
x1: 278 x2: 499 y1: 0 y2: 158
 	 The image with the result is saved ?: out\img\1687092874.7793007_16_2_chair
Saving all!
x1: 277 x2: 411 y1: 0 y2: 125
 	 The image with the result is saved ?: out\img\1687092874.7793007_16_3_tv
Saving all!
x1: 0 x2: 170

pred i 0 tensor([[6.53815e+01, 9.40762e+00, 2.24478e+02, 2.72968e+02, 9.25853e-01, 0.00000e+00],
        [8.63800e-02, 2.18646e+01, 1.25380e+02, 1.65960e+02, 8.64472e-01, 6.30000e+01],
        [2.09129e+02, 8.15211e+00, 3.74003e+02, 1.27502e+02, 5.14870e-01, 6.20000e+01],
        [2.08519e+02, 8.13509e+00, 3.74957e+02, 1.27478e+02, 4.13360e-01, 5.60000e+01],
        [8.25028e+01, 4.10961e+01, 1.19617e+02, 6.71155e+01, 3.46232e-01, 7.30000e+01]])
save_path: out\stream2
x1: 110 x2: 159 y1: 43 y2: 77
 	 The image with the result is saved ?: out\img\1687092878.321013_21_1_book
Saving all!
x1: 278 x2: 500 y1: 0 y2: 158
 	 The image with the result is saved ?: out\img\1687092878.321013_21_2_chair
Saving all!
x1: 279 x2: 499 y1: 0 y2: 158
 	 The image with the result is saved ?: out\img\1687092878.321013_21_3_tv
Saving all!
x1: 0 x2: 167 y1: 17 y2: 209
 	 The image with the result is saved ?: out\img\1687092878.321013_21_4_laptop
Saving all!
x1: 87 x2: 299 y1: 1 y2: 352
 	 The image with the 

Nose coordinates: (243.86366939544678, 36.016825675964355)
Foot Left coordinates: (8.005264043807983, 231.68613862991333)
Foot Right coordinates: (40.28570890426636, 257.10031175613403)
[[     16.965      304.41]] prediction  [    0.21001      3.2627]
center (21, 326)
[[     85.374       337.8]] prediction  [    0.71823      3.4005]
center (71, 340)
 3D A
 3D B
 	 The image with the result is saved ?: out\img3D\1687092881.4600892_11
 3D C
Saving all!
SHAPES: (360, 640, 3) (360, 640, 3)
 The image with the result is saved ?: out\img\1687092881.4600892_25
TIMELINE: 1687092882.262439 1687092881.4600892
I)img# 1 im0s# 1
II)img# 1 im0s# 1
pred i 0 tensor([[2.31141e+02, 5.46679e+01, 4.23080e+02, 2.49475e+02, 9.56267e-01, 0.00000e+00],
        [9.37413e+01, 9.08699e+00, 1.75787e+02, 1.26726e+02, 7.86443e-01, 0.00000e+00],
        [2.93545e+02, 4.22646e+01, 3.39071e+02, 9.38573e+01, 7.17810e-01, 6.20000e+01],
        [2.10148e+02, 1.59931e+01, 3.01732e+02, 1.01859e+02, 5.57000e-01, 6.20000e+01

Box face: [224, 5, 50, 42]
 	 The face with the result is saved ?: out\faces\1687092884.1006303_28_8_person_0
Nose coordinates: (231.57312655448914, 28.131086826324463)
Foot Left coordinates: (45.237120509147644, 205.5914068222046)
Foot Right coordinates: (61.03246772289276, 199.63103771209717)
[[      104.9      308.39]] prediction  [    0.86305      3.1058]
center (86, 310)
[[     141.52      299.45]] prediction  [     1.1403      2.9465]
center (114, 294)
 3D A
 3D B
 	 The image with the result is saved ?: out\img3D\1687092884.1006303_8
 3D C
Saving all!
SHAPES: (360, 640, 3) (360, 640, 3)
 The image with the result is saved ?: out\img\1687092884.1006303_28
TIMELINE: 1687092885.0001774 1687092884.1006303
I)img# 1 im0s# 1
II)img# 1 im0s# 1
pred i 0 tensor([[2.97769e+02, 5.23690e+01, 4.42664e+02, 2.16174e+02, 8.89783e-01, 0.00000e+00],
        [1.27751e+02, 8.99255e+00, 1.84742e+02, 1.04990e+02, 8.65120e-01, 0.00000e+00],
        [1.70892e+02, 9.21477e+01, 2.14282e+02, 1.36289e+02, 5

Nose coordinates: (139.38281321525574, 22.35373890399933)
Foot Left coordinates: (0.7621547877788544, 179.10204088687897)
Foot Right coordinates: (17.600494116544724, 171.70290887355804)
[[     2.6949      312.99]] prediction  [    0.10752      3.3662]
center (10, 336)
[[     62.234      300.06]] prediction  [    0.54369      3.1273]
center (54, 312)
 3D A
 3D B
 	 The image with the result is saved ?: out\img3D\1687092886.7006912_9
 3D C
Saving all!
SHAPES: (360, 640, 3) (360, 640, 3)
 The image with the result is saved ?: out\img\1687092886.7006912_31
TIMELINE: 1687092887.574861 1687092886.7006912
I)img# 1 im0s# 1
II)img# 1 im0s# 1
pred i 0 tensor([[2.94211e+02, 3.91558e+01, 4.29560e+02, 1.93285e+02, 8.93301e-01, 0.00000e+00],
        [2.10441e+02, 9.32389e+00, 3.02916e+02, 1.03620e+02, 5.81132e-01, 6.20000e+01],
        [1.16406e+02, 9.47447e+00, 1.78819e+02, 1.11795e+02, 5.62751e-01, 0.00000e+00],
        [1.57728e+02, 8.29674e+00, 3.05357e+02, 1.04152e+02, 4.87631e-01, 5.70000e+01

Nose coordinates: (141.2429525256157, 26.21797353029251)
Foot Left coordinates: (-2.9314036667346954, 181.76150798797607)
Foot Right coordinates: (10.60817500948906, 180.91369599103928)
[[    -10.252      319.19]] prediction  [   0.014939      3.4459]
center (1, 344)
[[       37.1       317.7]] prediction  [    0.36013      3.3328]
center (36, 333)
 3D A
 3D B
 	 The image with the result is saved ?: out\img3D\1687092889.2466402_9
 3D C
Saving all!
SHAPES: (360, 640, 3) (360, 640, 3)
 The image with the result is saved ?: out\img\1687092889.2466402_34
TIMELINE: 1687092890.0447845 1687092889.2466402
I)img# 1 im0s# 1
II)img# 1 im0s# 1
pred i 0 tensor([[2.92951e+02, 4.00600e+01, 4.29304e+02, 1.93523e+02, 9.25919e-01, 0.00000e+00],
        [9.53696e+01, 9.87798e+00, 1.71604e+02, 1.04425e+02, 8.16802e-01, 0.00000e+00],
        [8.29999e+01, 4.13684e+01, 1.18930e+02, 6.67963e+01, 5.36643e-01, 7.30000e+01],
        [1.70817e+02, 9.19808e+01, 2.14058e+02, 1.36691e+02, 5.11283e-01, 2.60000e+01]

pred i 0 tensor([[2.87428e+02, 3.96490e+01, 4.30738e+02, 1.93244e+02, 9.14801e-01, 0.00000e+00],
        [9.54040e+01, 9.58326e+00, 1.71747e+02, 1.15731e+02, 7.69820e-01, 0.00000e+00],
        [2.10414e+02, 1.17500e+01, 3.03165e+02, 1.01273e+02, 6.28161e-01, 6.20000e+01],
        [1.70967e+02, 9.19399e+01, 2.14176e+02, 1.36071e+02, 4.83890e-01, 2.40000e+01],
        [1.71039e+02, 9.16630e+01, 2.14100e+02, 1.36590e+02, 4.53611e-01, 2.60000e+01],
        [5.56900e-01, 1.18828e+01, 1.28399e+02, 1.70707e+02, 4.47894e-01, 5.70000e+01],
        [1.57039e+02, 8.16382e+00, 3.05968e+02, 1.02387e+02, 4.46872e-01, 5.70000e+01],
        [8.25295e+01, 4.14052e+01, 1.19158e+02, 6.68744e+01, 3.78918e-01, 7.30000e+01],
        [1.12475e+01, 2.43958e+01, 7.60321e+01, 9.98143e+01, 3.43613e-01, 2.60000e+01],
        [3.36929e+02, 4.20304e+01, 3.48746e+02, 8.19361e+01, 3.28843e-01, 6.20000e+01],
        [8.29657e+01, 4.13944e+01, 1.19606e+02, 6.67616e+01, 3.15139e-01, 6.30000e+01],
        [1.53573e+02, 6

Nose coordinates: (139.0796184539795, 26.257989406585693)
Foot Left coordinates: (-14.784657955169678, 190.2889130115509)
Foot Right coordinates: (3.907914161682129, 180.59516501426697)
[[    -52.568       335.8]] prediction  [   -0.28425      3.6723]
center (-28, 367)
[[     13.895       318.7]] prediction  [     0.1904      3.3907]
center (19, 339)
 3D A
 3D B
 	 The image with the result is saved ?: out\img3D\1687092894.1987169_12
 3D C
Saving all!
SHAPES: (360, 640, 3) (360, 640, 3)
 The image with the result is saved ?: out\img\1687092894.1987169_40
TIMELINE: 1687092895.1122465 1687092894.1987169
I)img# 1 im0s# 1
II)img# 1 im0s# 1
pred i 0 tensor([[3.06441e+02, 2.97575e+01, 4.24322e+02, 1.48987e+02, 8.59130e-01, 0.00000e+00],
        [9.50268e+01, 9.84781e+00, 1.71699e+02, 1.07650e+02, 8.16013e-01, 0.00000e+00],
        [1.70988e+02, 9.19413e+01, 2.13808e+02, 1.36640e+02, 4.89931e-01, 2.60000e+01],
        [2.09538e+02, 9.08413e+01, 2.21520e+02, 1.04781e+02, 4.63433e-01, 6.50000e+

Nose coordinates: (130.8052829504013, 21.845898628234863)
Foot Left coordinates: (3.518160581588745, 158.0237387418747)
Foot Right coordinates: (12.857816219329834, 146.88638055324554)
[[     13.323      362.35]] prediction  [    0.19499      3.7562]
center (19, 375)
[[     48.692      336.81]] prediction  [    0.44788      3.4699]
center (44, 346)
 3D A
 3D B
 	 The image with the result is saved ?: out\img3D\1687092896.9995131_10
 3D C
Saving all!
SHAPES: (360, 640, 3) (360, 640, 3)
 The image with the result is saved ?: out\img\1687092896.9995131_43
TIMELINE: 1687092897.8731718 1687092896.9995131
I)img# 1 im0s# 1
II)img# 1 im0s# 1
pred i 0 tensor([[2.99128e+02, 2.15702e+01, 4.17674e+02, 1.36874e+02, 8.25222e-01, 0.00000e+00],
        [1.54660e+02, 8.53606e+00, 3.06758e+02, 1.04704e+02, 8.08526e-01, 5.70000e+01],
        [9.48905e+01, 1.01684e+01, 1.70993e+02, 1.26734e+02, 7.54077e-01, 0.00000e+00],
        [3.59661e-01, 2.28979e+01, 1.28158e+02, 1.71436e+02, 4.89896e-01, 2.80000e+01

Nose coordinates: (121.7939567565918, 22.043445110321045)
Foot Left coordinates: (-5.373029708862305, 184.84270858764648)
Foot Right coordinates: (11.942157745361328, 175.17413866519928)
[[    -21.492      365.62]] prediction  [  -0.053752      3.8538]
center (-5, 385)
[[     47.769       346.5]] prediction  [    0.44235      3.5533]
center (44, 355)
 3D A
 3D B
 	 The image with the result is saved ?: out\img3D\1687092899.7422068_9
 3D C
Saving all!
x1: 127 x2: 231 y1: 1 y2: 164
 	 The image with the result is saved ?: out\img\1687092899.7422068_46_10_person
Nose coordinates: (69.56829786300659, 7.641455680131912)
Foot Left coordinates: (33.30166745185852, 157.67721545696259)
Foot Right coordinates: (72.83485507965088, 118.68615877628326)
[[     204.93      348.24]] prediction  [     1.6167       3.232]
center (161, 323)
[[     448.21      262.13]] prediction  [     3.6158      1.8719]
center (361, 187)
 3D A
 3D B
 	 The image with the result is saved ?: out\img3D\1687092899.7422068_

Nose coordinates: (180.19215059280396, 30.57989227771759)
Foot Left coordinates: (10.29446330666542, 192.57516038417816)
Foot Right coordinates: (-0.6240234375, 162.10647082328796)
[[     30.932       343.2]] prediction  [    0.31906      3.5609]
center (31, 356)
[[     -1.875       288.9]] prediction  [   0.068529      3.1708]
center (6, 317)
 3D A
 3D B
 	 The image with the result is saved ?: out\img3D\1687092902.4240203_11
 3D C
Saving all!
SHAPES: (360, 640, 3) (360, 640, 3)
 The image with the result is saved ?: out\img\1687092902.4240203_49
TIMELINE: 1687092903.304818 1687092902.4240203
I)img# 1 im0s# 1
II)img# 1 im0s# 1
pred i 0 tensor([[ 3.02768e+02,  7.96901e+01,  4.63511e+02,  2.32356e+02,  9.57963e-01,  0.00000e+00],
        [ 1.21944e+02,  1.04938e+01,  1.73287e+02,  1.04086e+02,  7.14599e-01,  0.00000e+00],
        [ 7.95216e-01,  1.81378e+01,  1.28192e+02,  1.70432e+02,  6.17597e-01,  2.80000e+01],
        [ 1.55792e+02,  9.11545e+00,  3.05730e+02,  1.03011e+02,  5.02133

pred i 0 tensor([[ 3.05476e+02,  7.73047e+01,  4.62554e+02,  2.32083e+02,  9.63625e-01,  0.00000e+00],
        [ 1.18248e+02,  1.05443e+01,  1.75463e+02,  1.07548e+02,  6.00910e-01,  0.00000e+00],
        [-6.21643e-02,  1.31283e+01,  1.28950e+02,  1.70836e+02,  5.91546e-01,  2.80000e+01],
        [ 1.55764e+02,  8.88161e+00,  3.07015e+02,  1.01727e+02,  4.86910e-01,  5.70000e+01],
        [ 8.25230e+01,  4.10415e+01,  1.19175e+02,  6.66075e+01,  4.78482e-01,  7.30000e+01],
        [ 1.70522e+02,  9.18087e+01,  2.14071e+02,  1.36761e+02,  3.92138e-01,  2.60000e+01],
        [ 1.70536e+02,  9.22847e+01,  2.14103e+02,  1.36203e+02,  3.54219e-01,  2.40000e+01],
        [ 2.11115e+02,  9.85622e+00,  3.05071e+02,  1.00853e+02,  3.24586e-01,  6.20000e+01],
        [ 1.11399e+01,  2.39141e+01,  7.61323e+01,  1.00043e+02,  3.05367e-01,  2.60000e+01]])
save_path: out\stream2
x1: 15 x2: 102 y1: 20 y2: 121
 	 The image with the result is saved ?: out\img\1687092905.8905792_53_1_handbag
Saving all

pred i 0 tensor([[3.03673e+02, 7.47711e+01, 4.61354e+02, 2.32513e+02, 9.43486e-01, 0.00000e+00],
        [5.08026e-01, 9.70686e+00, 1.31309e+02, 1.71037e+02, 5.91512e-01, 2.80000e+01],
        [1.54597e+02, 8.49073e+00, 3.06291e+02, 1.03421e+02, 5.89995e-01, 5.70000e+01],
        [1.23738e+02, 9.04786e+00, 1.84666e+02, 1.06382e+02, 5.62320e-01, 0.00000e+00],
        [2.11643e+02, 1.00404e+01, 3.05140e+02, 1.01137e+02, 4.54563e-01, 6.20000e+01],
        [1.16385e+01, 2.40835e+01, 7.68246e+01, 1.00141e+02, 3.79515e-01, 2.60000e+01],
        [8.24443e+01, 4.12831e+01, 1.18741e+02, 6.68179e+01, 3.74464e-01, 7.30000e+01],
        [2.82758e+02, 4.35530e+01, 3.70488e+02, 1.28193e+02, 3.35801e-01, 5.60000e+01],
        [1.70893e+02, 9.21029e+01, 2.13974e+02, 1.36987e+02, 2.96920e-01, 2.60000e+01],
        [1.70959e+02, 9.25691e+01, 2.13926e+02, 1.36255e+02, 2.51428e-01, 2.40000e+01]])
save_path: out\stream2
x1: 228 x2: 285 y1: 111 y2: 170
 	 The image with the result is saved ?: out\img\168709

Nose coordinates: (179.86018657684326, 31.648234724998474)
Foot Left coordinates: (5.8412806391716, 195.8968561887741)
Foot Right coordinates: (-2.7952769696712494, 166.3004767894745)
[[     17.718      344.01]] prediction  [    0.22319      3.5952]
center (22, 359)
[[    -8.4786      292.04]] prediction  [   0.020986       3.212]
center (2, 321)
 3D A
 3D B
 	 The image with the result is saved ?: out\img3D\1687092910.4169996_10
 3D C
Saving all!
SHAPES: (360, 640, 3) (360, 640, 3)
 The image with the result is saved ?: out\img\1687092910.4169996_58
TIMELINE: 1687092911.26805 1687092910.4169996
I)img# 1 im0s# 1
II)img# 1 im0s# 1
pred i 0 tensor([[3.05190e+02, 7.84584e+01, 4.63334e+02, 2.32772e+02, 9.57399e-01, 0.00000e+00],
        [1.22028e+02, 9.28071e+00, 1.85394e+02, 1.06097e+02, 7.93007e-01, 0.00000e+00],
        [1.55680e+02, 8.54976e+00, 3.06722e+02, 1.03898e+02, 6.44463e-01, 5.70000e+01],
        [4.05663e-01, 9.87117e+00, 1.28802e+02, 1.70778e+02, 6.04678e-01, 5.70000e+01],
 

pred i 0 tensor([[3.05485e+02, 7.81906e+01, 4.63217e+02, 2.32399e+02, 9.62834e-01, 0.00000e+00],
        [1.05222e+02, 1.12896e+01, 1.71321e+02, 1.09019e+02, 8.35631e-01, 0.00000e+00],
        [1.55993e+02, 8.87051e+00, 3.07706e+02, 1.04419e+02, 5.44384e-01, 5.70000e+01],
        [1.70971e+02, 9.26247e+01, 2.14198e+02, 1.36398e+02, 4.79366e-01, 2.40000e+01],
        [4.29710e-01, 2.46078e+01, 1.27919e+02, 1.71817e+02, 4.69088e-01, 2.80000e+01],
        [8.17348e+01, 4.11351e+01, 1.19738e+02, 6.67792e+01, 3.25740e-01, 7.30000e+01],
        [8.21220e+01, 4.11765e+01, 1.19890e+02, 6.66116e+01, 3.13916e-01, 6.30000e+01],
        [1.71047e+02, 9.22312e+01, 2.14151e+02, 1.36941e+02, 3.03890e-01, 2.60000e+01],
        [2.71622e-01, 2.12792e+01, 1.27708e+02, 1.70484e+02, 3.02138e-01, 5.70000e+01],
        [1.52478e+02, 6.10977e+01, 3.19154e+02, 1.78277e+02, 2.96756e-01, 6.00000e+01],
        [2.82047e+02, 4.08946e+01, 3.28201e+02, 1.05352e+02, 2.73166e-01, 2.40000e+01],
        [1.13273e+01, 2

Nose coordinates: (189.53976345062256, 34.682296961545944)
Foot Left coordinates: (11.955067455768585, 216.43390953540802)
Foot Right coordinates: (-0.2099321484565735, 163.3077174425125)
[[     34.621      346.29]] prediction  [    0.34641       3.579]
center (34, 357)
[[   -0.60795      261.29]] prediction  [   0.071231      2.9294]
center (7, 292)
 3D A
 3D B
 	 The image with the result is saved ?: out\img3D\1687092915.864878_9
 3D C
Saving all!
SHAPES: (360, 640, 3) (360, 640, 3)
 The image with the result is saved ?: out\img\1687092915.864878_64
TIMELINE: 1687092916.683934 1687092915.864878
I)img# 1 im0s# 1
II)img# 1 im0s# 1
pred i 0 tensor([[2.68872e+02, 9.48563e+01, 4.64725e+02, 2.56514e+02, 9.47866e-01, 0.00000e+00],
        [1.01350e+02, 1.72295e+01, 1.70086e+02, 1.11156e+02, 7.65993e-01, 0.00000e+00],
        [4.28284e-01, 2.36250e+01, 1.28059e+02, 1.71463e+02, 5.70339e-01, 5.70000e+01],
        [2.10353e+02, 9.18350e+00, 3.04660e+02, 1.03669e+02, 4.59541e-01, 6.20000e+01],


Nose coordinates: (243.4570598602295, 46.38737404346466)
Foot Left coordinates: (29.936120808124542, 237.6479902267456)
Foot Right coordinates: (11.480132341384888, 201.6221153140068)
[[     66.066      343.59]] prediction  [    0.57616      3.4904]
center (57, 349)
[[     25.335       291.5]] prediction  [    0.26914       3.134]
center (26, 313)
 3D A
 3D B
 	 The image with the result is saved ?: out\img3D\1687092918.4573345_10
 3D C
Saving all!
SHAPES: (360, 640, 3) (360, 640, 3)
 The image with the result is saved ?: out\img\1687092918.4573345_67
TIMELINE: 1687092919.4415226 1687092918.4573345
I)img# 1 im0s# 1
II)img# 1 im0s# 1
pred i 0 tensor([[2.31288e+02, 7.91065e+01, 4.39288e+02, 2.77524e+02, 9.61703e-01, 0.00000e+00],
        [1.01069e+02, 1.00723e+01, 1.71101e+02, 1.07419e+02, 8.71248e-01, 0.00000e+00],
        [1.56582e+02, 8.25999e+00, 3.05894e+02, 1.04324e+02, 6.14634e-01, 5.70000e+01],
        [8.18038e+01, 3.12686e+01, 1.22372e+02, 6.73848e+01, 5.18183e-01, 6.30000e+01]

Nose coordinates: (229.34242486953735, 49.05395418405533)
Foot Left coordinates: (14.778482168912888, 256.7913163304329)
Foot Right coordinates: (13.15009891986847, 219.0926971435547)
[[     34.394      346.24]] prediction  [    0.34475       3.579]
center (34, 357)
[[     30.604      295.41]] prediction  [     0.3087      3.1561]
center (30, 315)
 3D A
 3D B
 	 The image with the result is saved ?: out\img3D\1687092921.3139446_11
 3D C
Saving all!
SHAPES: (360, 640, 3) (360, 640, 3)
 The image with the result is saved ?: out\img\1687092921.3139446_70
TIMELINE: 1687092922.2425947 1687092921.3139446
I)img# 1 im0s# 1
II)img# 1 im0s# 1
pred i 0 tensor([[2.29583e+02, 7.50779e+01, 4.35037e+02, 2.77036e+02, 9.62349e-01, 0.00000e+00],
        [1.00757e+02, 9.57744e+00, 1.71663e+02, 1.09228e+02, 8.64123e-01, 0.00000e+00],
        [1.54193e+02, 8.69783e+00, 3.07876e+02, 1.05970e+02, 5.29992e-01, 5.70000e+01],
        [3.77857e-01, 1.98316e+01, 1.28101e+02, 1.71474e+02, 4.00398e-01, 2.80000e+01]

Nose coordinates: (222.63388395309448, 47.99478152394295)
Foot Left coordinates: (11.024651527404785, 263.7116053700447)
Foot Right coordinates: (9.90479439496994, 220.7548770904541)
[[     26.133      352.92]] prediction  [    0.28583      3.6519]
center (28, 365)
[[     23.478      295.43]] prediction  [    0.25616      3.1719]
center (25, 317)
 3D A
 3D B
 	 The image with the result is saved ?: out\img3D\1687092924.047193_10
 3D C
Saving all!
SHAPES: (360, 640, 3) (360, 640, 3)
 The image with the result is saved ?: out\img\1687092924.047193_73
TIMELINE: 1687092924.8890862 1687092924.047193
I)img# 1 im0s# 1
II)img# 1 im0s# 1
pred i 0 tensor([[2.32808e+02, 7.60771e+01, 4.35930e+02, 2.76791e+02, 9.63409e-01, 0.00000e+00],
        [1.00267e+02, 9.14934e+00, 1.71576e+02, 1.12391e+02, 8.54465e-01, 0.00000e+00],
        [2.82273e+02, 3.58590e+01, 3.22945e+02, 1.05630e+02, 4.87681e-01, 2.40000e+01],
        [2.10656e+02, 9.59177e+00, 3.11608e+02, 1.04600e+02, 3.65500e-01, 6.20000e+01],
  

Nose coordinates: (247.81219053268433, 48.59738424420357)
Foot Left coordinates: (6.925532341003418, 254.7076380252838)
Foot Right coordinates: (29.986650109291077, 235.9576565027237)
[[     15.076      346.02]] prediction  [    0.20443      3.6174]
center (20, 361)
[[     65.277      320.55]] prediction  [    0.56825      3.2966]
center (56, 329)
 3D A
 3D B
 	 The image with the result is saved ?: out\img3D\1687092926.694783_9
 3D C
Saving all!
SHAPES: (360, 640, 3) (360, 640, 3)
 The image with the result is saved ?: out\img\1687092926.694783_76
TIMELINE: 1687092927.5543883 1687092926.694783
I)img# 1 im0s# 1
II)img# 1 im0s# 1
pred i 0 tensor([[1.93327e+02, 6.12618e+01, 4.14465e+02, 2.70732e+02, 9.52036e-01, 0.00000e+00],
        [1.00211e+02, 1.01070e+01, 1.70663e+02, 1.15708e+02, 8.49458e-01, 0.00000e+00],
        [1.57951e+02, 8.51950e+00, 3.07207e+02, 1.03817e+02, 7.25792e-01, 5.70000e+01],
        [2.88654e-01, 2.47553e+01, 1.27885e+02, 1.71616e+02, 5.39267e-01, 5.70000e+01],
  

Nose coordinates: (219.60146576166153, 57.28011429309845)
Foot Left coordinates: (9.165764600038528, 281.5726351737976)
Foot Right coordinates: (-0.4287630319595337, 244.1180169582367)
[[     21.331      343.61]] prediction  [    0.24933      3.5843]
center (24, 358)
[[   -0.99785      297.91]] prediction  [   0.077087      3.2459]
center (7, 324)
 3D A
 3D B
 	 The image with the result is saved ?: out\img3D\1687092929.280592_10
 3D C
Saving all!
SHAPES: (360, 640, 3) (360, 640, 3)
 The image with the result is saved ?: out\img\1687092929.280592_79
TIMELINE: 1687092930.1957722 1687092929.280592
I)img# 1 im0s# 1
II)img# 1 im0s# 1
pred i 0 tensor([[1.90955e+02, 5.25784e+01, 4.01268e+02, 2.70033e+02, 9.45417e-01, 0.00000e+00],
        [1.00352e+02, 9.90691e+00, 1.71018e+02, 1.12816e+02, 8.37945e-01, 0.00000e+00],
        [1.55194e+02, 8.48229e+00, 3.06835e+02, 1.03958e+02, 7.18228e-01, 5.70000e+01],
        [6.82335e-01, 4.78940e+01, 1.27722e+02, 1.71515e+02, 6.28951e-01, 2.80000e+01],
 

Nose coordinates: (239.36927491426468, 56.57011789083481)
Foot Left coordinates: (19.995084643363953, 265.3788987994194)
Foot Right coordinates: (5.650362491607666, 226.77939569950104)
[[     42.799      342.42]] prediction  [    0.40549      3.5295]
center (40, 352)
[[     12.094      292.62]] prediction  [    0.17186      3.1724]
center (17, 317)
 3D A
 3D B
 	 The image with the result is saved ?: out\img3D\1687092931.9231396_9
 3D C
Saving all!
SHAPES: (360, 640, 3) (360, 640, 3)
 The image with the result is saved ?: out\img\1687092931.9231396_82
TIMELINE: 1687092932.751146 1687092931.9231396
I)img# 1 im0s# 1
II)img# 1 im0s# 1
pred i 0 tensor([[1.84975e+02, 6.24232e+01, 4.09006e+02, 2.70356e+02, 9.63381e-01, 0.00000e+00],
        [9.44738e+01, 9.76731e+00, 1.68043e+02, 1.07975e+02, 9.06131e-01, 0.00000e+00],
        [1.57162e+02, 8.48888e+00, 3.06795e+02, 1.01551e+02, 5.61727e-01, 5.70000e+01],
        [8.29076e+01, 4.12600e+01, 1.19250e+02, 6.64121e+01, 4.33265e-01, 6.30000e+01],

Nose coordinates: (240.50460290908813, 52.81736034154892)
Foot Left coordinates: (22.566084623336792, 262.5131211876869)
Foot Right coordinates: (5.353208005428314, 224.43589401245117)
[[     47.664      341.17]] prediction  [    0.44091      3.5088]
center (44, 350)
[[     11.307      291.69]] prediction  [    0.16588      3.1661]
center (16, 316)
 3D A
 3D B
 	 The image with the result is saved ?: out\img3D\1687092935.2544248_7
 3D C
Saving all!
SHAPES: (360, 640, 3) (360, 640, 3)
 The image with the result is saved ?: out\img\1687092935.2544248_86
TIMELINE: 1687092936.0561852 1687092935.2544248
I)img# 1 im0s# 1
II)img# 1 im0s# 1
pred i 0 tensor([[1.84167e+02, 6.36742e+01, 4.09655e+02, 2.69918e+02, 9.59081e-01, 0.00000e+00],
        [1.24188e+02, 9.50348e+00, 1.85122e+02, 1.06670e+02, 8.53090e-01, 0.00000e+00],
        [1.55379e+02, 8.55576e+00, 3.07058e+02, 1.03112e+02, 6.80844e-01, 5.70000e+01],
        [2.80983e-01, 1.00920e+01, 1.29748e+02, 1.70399e+02, 5.93239e-01, 2.80000e+01]

Nose coordinates: (236.46540069580078, 59.67399403452873)
Foot Left coordinates: (0.914637565612793, 275.9777069091797)
Foot Right coordinates: (13.240662574768066, 227.99260318279266)
[[     2.0325      361.28]] prediction  [    0.11354      3.7705]
center (11, 377)
[[     29.424      298.46]] prediction  [    0.30052       3.185]
center (30, 318)
 3D A
 3D B
 	 The image with the result is saved ?: out\img3D\1687092937.7964058_10
 3D C
Saving all!
SHAPES: (360, 640, 3) (360, 640, 3)
 The image with the result is saved ?: out\img\1687092937.7964058_89
TIMELINE: 1687092938.6147454 1687092937.7964058
I)img# 1 im0s# 1
II)img# 1 im0s# 1
pred i 0 tensor([[2.15315e+02, 1.06399e+02, 4.62154e+02, 2.73846e+02, 9.59266e-01, 0.00000e+00],
        [1.23567e+02, 9.14269e+00, 1.85163e+02, 1.08049e+02, 8.72056e-01, 0.00000e+00],
        [2.01210e-01, 9.89361e+00, 1.28335e+02, 1.70483e+02, 6.47696e-01, 5.70000e+01],
        [1.55192e+02, 8.25934e+00, 3.07879e+02, 1.11860e+02, 5.83828e-01, 5.70000e+01

pred i 0 tensor([[1.58790e+02, 8.25800e+01, 4.19542e+02, 2.69957e+02, 9.61940e-01, 0.00000e+00],
        [3.32963e+02, 1.71359e+02, 3.96190e+02, 2.25389e+02, 7.24741e-01, 6.30000e+01],
        [1.56505e+02, 8.60021e+00, 3.06855e+02, 1.03016e+02, 6.03661e-01, 5.70000e+01],
        [2.09781e+02, 9.94008e+00, 3.06256e+02, 1.01612e+02, 4.12462e-01, 6.20000e+01],
        [1.36017e-01, 9.61585e+00, 1.28911e+02, 1.70195e+02, 4.09189e-01, 5.70000e+01],
        [1.70477e+02, 9.18614e+01, 2.13885e+02, 1.36710e+02, 3.37092e-01, 2.60000e+01],
        [8.25605e+01, 4.12135e+01, 1.20391e+02, 6.68774e+01, 3.34902e-01, 7.30000e+01],
        [1.20648e+02, 1.18127e+01, 1.83152e+02, 1.14080e+02, 3.25904e-01, 0.00000e+00],
        [1.70508e+02, 9.21822e+01, 2.14087e+02, 1.36111e+02, 3.23573e-01, 2.40000e+01]])
save_path: out\stream2
x1: 227 x2: 285 y1: 111 y2: 169
 	 The image with the result is saved ?: out\img\1687092941.236045_93_1_backpack
Saving all!
x1: 161 x2: 244 y1: 4 y2: 140
 	 The image with th

pred i 0 tensor([[1.56059e+02, 7.90830e+01, 4.16240e+02, 2.70977e+02, 9.59755e-01, 0.00000e+00],
        [1.14927e+02, 9.19146e+00, 1.77208e+02, 1.13614e+02, 7.79063e-01, 0.00000e+00],
        [3.30474e+02, 1.67265e+02, 3.97462e+02, 2.19907e+02, 6.81924e-01, 6.30000e+01],
        [1.57675e+02, 8.45824e+00, 3.07097e+02, 1.04765e+02, 5.95594e-01, 5.70000e+01],
        [4.00967e-01, 1.00577e+01, 1.27946e+02, 1.70497e+02, 5.02610e-01, 5.70000e+01],
        [2.81888e+02, 3.60206e+01, 3.29870e+02, 1.06688e+02, 4.68586e-01, 2.40000e+01],
        [1.70571e+02, 9.23053e+01, 2.14030e+02, 1.36166e+02, 3.90657e-01, 2.40000e+01],
        [2.08642e+02, 9.44263e+00, 3.05621e+02, 1.03401e+02, 3.55544e-01, 6.20000e+01],
        [8.19170e+01, 4.12964e+01, 1.19996e+02, 6.71122e+01, 3.03466e-01, 7.30000e+01],
        [1.07409e+01, 2.47719e+01, 7.64089e+01, 1.00233e+02, 2.52262e-01, 2.60000e+01]])
save_path: out\stream2
x1: 14 x2: 102 y1: 21 y2: 122
 	 The image with the result is saved ?: out\img\16870929

Nose coordinates: (312.9114031791687, 68.07201582193375)
Foot Left coordinates: (179.44325923919678, 252.40688687562943)
Foot Right coordinates: (8.918763399124146, 219.90730619430542)
[[     332.88      353.57]] prediction  [     2.6099      2.9945]
center (260, 299)
[[     16.545      308.04]] prediction  [    0.20765      3.2946]
center (20, 329)
 3D A
 3D B
 	 The image with the result is saved ?: out\img3D\1687092945.562233_9
 3D C
Saving all!
SHAPES: (360, 640, 3) (360, 640, 3)
 The image with the result is saved ?: out\img\1687092945.562233_98
TIMELINE: 1687092946.50779 1687092945.562233
I)img# 1 im0s# 1
II)img# 1 im0s# 1
pred i 0 tensor([[1.55969e+02, 8.04439e+01, 4.15998e+02, 2.70769e+02, 9.60536e-01, 0.00000e+00],
        [1.12848e+02, 9.11277e+00, 1.77899e+02, 1.13512e+02, 7.45042e-01, 0.00000e+00],
        [3.29273e+02, 1.65642e+02, 3.96220e+02, 2.20095e+02, 6.96848e-01, 6.30000e+01],
        [1.57033e+02, 8.55994e+00, 3.08029e+02, 1.03809e+02, 6.43572e-01, 5.70000e+01],
  

Nose coordinates: (313.42250967025757, 67.93893992900848)
Foot Left coordinates: (183.51162803173065, 246.7970724105835)
Foot Right coordinates: (7.211523056030273, 220.04564690589905)
[[     339.44      349.79]] prediction  [      2.664      2.9461]
center (266, 294)
[[     13.339      311.88]] prediction  [    0.18496      3.3341]
center (18, 333)
 3D A
 3D B
 	 The image with the result is saved ?: out\img3D\1687092948.3429255_10
 3D C
Saving all!
SHAPES: (360, 640, 3) (360, 640, 3)
 The image with the result is saved ?: out\img\1687092948.3429255_101
TIMELINE: 1687092949.2089553 1687092948.3429255
I)img# 1 im0s# 1
II)img# 1 im0s# 1
pred i 0 tensor([[1.55957e+02, 8.20580e+01, 4.16497e+02, 2.70551e+02, 9.42297e-01, 0.00000e+00],
        [3.29294e+02, 1.66622e+02, 3.91053e+02, 2.21907e+02, 7.51459e-01, 6.30000e+01],
        [1.17700e+02, 9.17128e+00, 1.82398e+02, 1.11060e+02, 6.48919e-01, 0.00000e+00],
        [1.57330e+02, 8.58552e+00, 3.07031e+02, 1.04472e+02, 5.19475e-01, 5.70000e+

Nose coordinates: (55.00111198425293, 7.540621757507324)
Foot Left coordinates: (-5.500715017318726, 147.61008310317993)
Foot Right coordinates: (51.795729875564575, 107.68793654441833)
[[     -41.91      374.22]] prediction  [   -0.19624      3.9647]
center (-19, 396)
[[     394.63      273.01]] prediction  [     3.1593        2.11]
center (315, 211)
 3D A
 3D B
 	 The image with the result is saved ?: out\img3D\1687092951.021415_10
 3D C
Saving all!
x1: 208 x2: 555 y1: 97 y2: 349
 	 The image with the result is saved ?: out\img\1687092951.021415_104_11_person
Nose coordinates: (310.94739788770676, 68.94120240211487)
Foot Left coordinates: (178.22906285524368, 247.81238079071045)
Foot Right coordinates: (4.573734615929425, 214.53862524032593)
[[     328.72      354.02]] prediction  [     2.5768      3.0079]
center (257, 300)
[[     8.4357      306.48]] prediction  [    0.14798      3.2987]
center (14, 329)
 3D A
 3D B
 	 The image with the result is saved ?: out\img3D\1687092951.02141

Nose coordinates: (312.6046345233917, 67.92702412605286)
Foot Left coordinates: (181.13566958904266, 246.33706378936768)
Foot Right coordinates: (5.564512491226196, 216.0460685491562)
[[     335.05      350.52]] prediction  [     2.6287      2.9625]
center (262, 296)
[[     10.293      307.42]] prediction  [    0.16176      3.3027]
center (16, 330)
 3D A
 3D B
 	 The image with the result is saved ?: out\img3D\1687092953.7512617_11
 3D C
Saving all!
SHAPES: (360, 640, 3) (360, 640, 3)
 The image with the result is saved ?: out\img\1687092953.7512617_107
TIMELINE: 1687092954.578867 1687092953.7512617
I)img# 1 im0s# 1
II)img# 1 im0s# 1
pred i 0 tensor([[1.55755e+02, 8.11463e+01, 4.15512e+02, 2.70881e+02, 9.59900e-01, 0.00000e+00],
        [1.13993e+02, 9.21884e+00, 1.85162e+02, 1.06924e+02, 7.88000e-01, 0.00000e+00],
        [3.29770e+02, 1.68228e+02, 3.93156e+02, 2.19238e+02, 7.06861e-01, 6.30000e+01],
        [1.55844e+02, 8.44016e+00, 3.07109e+02, 1.03469e+02, 6.41248e-01, 5.70000e+01

[[      53.14      354.67]] prediction  [    0.48259      3.6104]
center (48, 361)
[[     310.28      327.04]] prediction  [      2.444      2.8091]
center (244, 280)
 3D A
 3D B
 	 The image with the result is saved ?: out\img3D\1687092956.3141375_10
 3D C
Saving all!
x1: 208 x2: 554 y1: 96 y2: 349
 	 The image with the result is saved ?: out\img\1687092956.3141375_110_11_person
Nose coordinates: (312.16486525535583, 67.72230592370033)
Foot Left coordinates: (179.78637564182281, 249.00692814588547)
Foot Right coordinates: (3.584024667739868, 219.38384008407593)
[[     332.55      354.32]] prediction  [     2.6069      3.0019]
center (260, 300)
[[     6.6294      312.17]] prediction  [    0.13602      3.3508]
center (13, 335)
 3D A
 3D B
 	 The image with the result is saved ?: out\img3D\1687092956.3141375_11
 3D C
Saving all!
SHAPES: (360, 640, 3) (360, 640, 3)
 The image with the result is saved ?: out\img\1687092956.3141375_110
TIMELINE: 1687092957.229539 1687092956.3141375
I)img# 1

Nose coordinates: (315.78385305404663, 67.82350569963455)
Foot Left coordinates: (203.1465629339218, 242.04818558692932)
Foot Right coordinates: (13.123161971569061, 206.47751569747925)
[[     367.27      354.22]] prediction  [     2.8832      2.9223]
center (288, 292)
[[     23.725      302.16]] prediction  [    0.25922       3.229]
center (25, 322)
 3D A
 3D B
 	 The image with the result is saved ?: out\img3D\1687092959.166649_9
 3D C
Saving all!
SHAPES: (360, 640, 3) (360, 640, 3)
 The image with the result is saved ?: out\img\1687092959.166649_113
TIMELINE: 1687092960.0906084 1687092959.166649
I)img# 1 im0s# 1
II)img# 1 im0s# 1
pred i 0 tensor([[1.42906e+02, 8.37331e+01, 4.03189e+02, 2.71672e+02, 9.55716e-01, 0.00000e+00],
        [1.19585e+02, 9.20701e+00, 1.82028e+02, 1.04191e+02, 8.40011e-01, 0.00000e+00],
        [3.22225e+02, 1.68859e+02, 3.86777e+02, 2.22104e+02, 6.63882e-01, 6.30000e+01],
        [1.55267e+02, 8.72667e+00, 3.07731e+02, 1.04427e+02, 6.55998e-01, 5.70000e+01]

Nose coordinates: (312.40279519557953, 68.68522614240646)
Foot Left coordinates: (211.83411765098572, 245.71457505226135)
Foot Right coordinates: (13.332635283470154, 208.9998722076416)
[[     391.83      353.83]] prediction  [     3.0806      2.8626]
center (308, 286)
[[     24.662      300.96]] prediction  [    0.26589      3.2167]
center (26, 321)
 3D A
 3D B
 	 The image with the result is saved ?: out\img3D\1687092961.873478_10
 3D C
Saving all!
SHAPES: (360, 640, 3) (360, 640, 3)
 The image with the result is saved ?: out\img\1687092961.873478_116
TIMELINE: 1687092962.7865484 1687092961.873478
I)img# 1 im0s# 1
II)img# 1 im0s# 1
pred i 0 tensor([[1.38585e+02, 4.60604e+01, 3.29602e+02, 2.70878e+02, 9.20314e-01, 0.00000e+00],
        [1.18808e+02, 9.28076e+00, 1.83217e+02, 1.06678e+02, 8.13147e-01, 0.00000e+00],
        [2.70927e+02, 1.59860e+02, 3.57577e+02, 2.21108e+02, 7.13711e-01, 6.30000e+01],
        [1.54031e+02, 8.53165e+00, 3.07268e+02, 9.52523e+01, 6.24676e-01, 5.70000e+01

TIMELINE: 1687092966.206195 1687092965.491634
I)img# 1 im0s# 1
II)img# 1 im0s# 1
pred i 0 tensor([[2.30066e+01, 9.53842e+00, 1.80498e+02, 2.45521e+02, 8.38446e-01, 0.00000e+00],
        [1.95939e+02, 1.44502e+02, 2.64038e+02, 1.65222e+02, 4.71420e-01, 7.30000e+01],
        [1.65487e+02, 8.67753e+00, 3.06971e+02, 1.01449e+02, 4.27913e-01, 5.70000e+01],
        [1.95031e+02, 1.44417e+02, 2.64304e+02, 1.64609e+02, 3.84933e-01, 6.50000e+01],
        [1.88541e+02, 9.24934e+01, 2.08751e+02, 1.16737e+02, 3.81849e-01, 6.50000e+01],
        [8.38048e+01, 9.16880e+01, 2.00195e+02, 1.72185e+02, 2.76004e-01, 6.30000e+01],
        [3.05415e+02, 1.14095e+02, 3.87778e+02, 1.93839e+02, 2.74654e-01, 5.60000e+01]])
save_path: out\stream2
x1: 407 x2: 517 y1: 140 y2: 246
 	 The image with the result is saved ?: out\img\1687092966.206195_121_1_chair
Saving all!
x1: 112 x2: 267 y1: 110 y2: 218
 	 The image with the result is saved ?: out\img\1687092966.206195_121_2_laptop
Saving all!
x1: 251 x2: 278 y1: 111

TIMELINE: 1687092968.9766858 1687092968.222529
I)img# 1 im0s# 1
II)img# 1 im0s# 1
pred i 0 tensor([[1.15199e+02, 9.56201e+00, 1.78791e+02, 1.06045e+02, 7.69310e-01, 0.00000e+00],
        [1.56951e+02, 8.93154e+00, 3.06542e+02, 1.05692e+02, 5.96852e-01, 5.70000e+01],
        [1.70884e+02, 9.18792e+01, 2.13872e+02, 1.36682e+02, 5.04430e-01, 2.60000e+01],
        [1.70871e+02, 9.22696e+01, 2.14038e+02, 1.36362e+02, 4.29493e-01, 2.40000e+01],
        [8.26684e+01, 4.13631e+01, 1.19270e+02, 6.62383e+01, 4.01357e-01, 7.30000e+01],
        [1.52843e+02, 6.16462e+01, 3.17272e+02, 1.72619e+02, 3.48296e-01, 6.00000e+01],
        [9.83528e-01, 1.06047e+01, 1.27578e+02, 1.70350e+02, 2.92398e-01, 2.80000e+01],
        [8.71075e-01, 1.02427e+01, 1.27514e+02, 1.70262e+02, 2.81338e-01, 5.70000e+01],
        [3.06367e+02, 1.13452e+02, 3.87843e+02, 1.94111e+02, 2.72223e-01, 5.60000e+01]])
save_path: out\stream2
x1: 408 x2: 517 y1: 139 y2: 247
 	 The image with the result is saved ?: out\img\1687092968.9

pred i 0 tensor([[1.21343e+02, 9.01487e+00, 1.85294e+02, 1.06285e+02, 8.57388e-01, 0.00000e+00],
        [1.57915e+02, 8.47731e+00, 3.06000e+02, 1.02671e+02, 7.96854e-01, 5.70000e+01],
        [3.03839e+02, 1.06143e+02, 3.88343e+02, 1.93920e+02, 5.61689e-01, 5.60000e+01],
        [1.70876e+02, 9.19918e+01, 2.13874e+02, 1.36864e+02, 5.51220e-01, 2.60000e+01],
        [8.00564e-01, 1.31905e+01, 1.28430e+02, 1.70533e+02, 4.31825e-01, 5.70000e+01],
        [1.11929e+01, 2.72237e+01, 7.55125e+01, 9.97364e+01, 4.26911e-01, 2.60000e+01],
        [1.70669e+02, 9.25562e+01, 2.14103e+02, 1.36311e+02, 4.26713e-01, 2.40000e+01],
        [8.24953e+01, 4.12110e+01, 1.19484e+02, 6.66859e+01, 4.11099e-01, 7.30000e+01],
        [1.54654e+02, 6.32356e+01, 3.16287e+02, 1.73118e+02, 3.17199e-01, 6.00000e+01]])
save_path: out\stream2
x1: 206 x2: 422 y1: 72 y2: 219
 	 The image with the result is saved ?: out\img\1687092971.7641287_129_1_dining table
Saving all!
x1: 110 x2: 159 y1: 43 y2: 77
 	 The image wi

TIMELINE: 1687092974.547157 1687092973.8168023
I)img# 1 im0s# 1
II)img# 1 im0s# 1
pred i 0 tensor([[1.18351e+02, 1.69901e+01, 1.70906e+02, 1.07885e+02, 8.03305e-01, 0.00000e+00],
        [1.57516e+02, 8.57899e+00, 3.06349e+02, 1.03316e+02, 6.00897e-01, 5.70000e+01],
        [1.70863e+02, 9.20303e+01, 2.13917e+02, 1.36937e+02, 5.14171e-01, 2.60000e+01],
        [1.05673e+01, 2.84337e+01, 7.60065e+01, 1.00130e+02, 4.93199e-01, 2.60000e+01],
        [7.61101e-01, 1.35014e+01, 1.27835e+02, 1.70520e+02, 4.49003e-01, 2.80000e+01],
        [1.70829e+02, 9.24385e+01, 2.14067e+02, 1.36454e+02, 4.32206e-01, 2.40000e+01],
        [3.06872e+02, 1.13112e+02, 3.88994e+02, 1.93760e+02, 3.91840e-01, 5.60000e+01],
        [8.32616e+01, 4.14785e+01, 1.19238e+02, 6.65102e+01, 3.61044e-01, 7.30000e+01],
        [2.10810e+02, 1.00317e+01, 3.03263e+02, 1.02572e+02, 3.04251e-01, 6.20000e+01],
        [1.52963e+02, 6.16245e+01, 3.16779e+02, 1.73033e+02, 2.86782e-01, 6.00000e+01]])
save_path: out\stream2
x1: 2

TIMELINE: 1687092977.3410223 1687092976.618435
I)img# 1 im0s# 1
II)img# 1 im0s# 1
pred i 0 tensor([[1.22717e+02, 8.85143e+00, 1.84222e+02, 1.06902e+02, 8.63102e-01, 0.00000e+00],
        [1.70928e+02, 9.20552e+01, 2.14259e+02, 1.36210e+02, 5.52387e-01, 2.40000e+01],
        [1.58096e+02, 8.84728e+00, 3.05802e+02, 1.01447e+02, 5.14374e-01, 5.70000e+01],
        [1.70895e+02, 9.16754e+01, 2.14013e+02, 1.36709e+02, 4.28173e-01, 2.60000e+01],
        [1.06874e+01, 2.82999e+01, 7.54297e+01, 9.92998e+01, 4.00756e-01, 2.60000e+01],
        [3.06350e+02, 1.12495e+02, 3.88412e+02, 1.94268e+02, 3.98542e-01, 5.60000e+01],
        [1.30276e+00, 7.58168e+01, 1.26875e+02, 1.70629e+02, 3.97788e-01, 2.80000e+01],
        [8.26874e+01, 4.12948e+01, 1.19540e+02, 6.65474e+01, 3.51895e-01, 7.30000e+01],
        [1.52857e+02, 6.18955e+01, 3.16897e+02, 1.73090e+02, 3.29179e-01, 6.00000e+01],
        [2.10451e+02, 8.05113e+00, 3.74670e+02, 1.29416e+02, 2.67894e-01, 5.60000e+01],
        [1.06601e+01, 2.83013

pred i 0 tensor([[1.23112e+02, 9.64688e+00, 1.83863e+02, 1.07482e+02, 7.86270e-01, 0.00000e+00],
        [1.57138e+02, 8.28792e+00, 3.05820e+02, 1.03603e+02, 6.79251e-01, 5.70000e+01],
        [1.70723e+02, 9.23316e+01, 2.14122e+02, 1.36282e+02, 4.75014e-01, 2.40000e+01],
        [1.07422e+01, 2.86151e+01, 7.46188e+01, 9.96192e+01, 4.71130e-01, 2.60000e+01],
        [1.70776e+02, 9.20430e+01, 2.13693e+02, 1.36796e+02, 4.62733e-01, 2.60000e+01],
        [7.83089e-01, 1.62668e+01, 1.27676e+02, 1.70906e+02, 4.25243e-01, 5.70000e+01],
        [8.29804e+01, 4.09755e+01, 1.20165e+02, 6.63103e+01, 3.85253e-01, 7.30000e+01],
        [3.06302e+02, 1.12834e+02, 3.88290e+02, 1.93761e+02, 3.56265e-01, 5.60000e+01],
        [2.09389e+02, 9.44177e+00, 3.03578e+02, 1.02298e+02, 2.77701e-01, 6.20000e+01],
        [1.54556e+02, 6.28785e+01, 3.17082e+02, 1.73163e+02, 2.59091e-01, 6.00000e+01]])
save_path: out\stream2
x1: 206 x2: 423 y1: 72 y2: 219
 	 The image with the result is saved ?: out\img\1687092

pred i 0 tensor([[1.54140e+02, 8.44865e+00, 3.06686e+02, 1.04660e+02, 5.55824e-01, 5.70000e+01],
        [3.68355e-01, 1.89287e+01, 7.13297e+01, 2.01683e+02, 4.53969e-01, 0.00000e+00],
        [3.06186e+02, 1.14028e+02, 3.87297e+02, 1.94560e+02, 3.99874e-01, 5.60000e+01],
        [1.70826e+02, 9.20090e+01, 2.13683e+02, 1.36520e+02, 3.80780e-01, 2.60000e+01],
        [3.80334e+02, 1.78338e+02, 4.01364e+02, 2.08707e+02, 3.34105e-01, 7.50000e+01],
        [4.06957e+01, 7.62937e+01, 1.27245e+02, 1.70988e+02, 3.20404e-01, 2.80000e+01],
        [3.86780e+02, 1.30683e+02, 4.49216e+02, 2.06957e+02, 2.52868e-01, 5.80000e+01]])
save_path: out\stream2
x1: 516 x2: 599 y1: 162 y2: 264
 	 The image with the result is saved ?: out\img\1687092983.0575006_145_1_potted plant
Saving all!
x1: 54 x2: 170 y1: 90 y2: 216
 	 The image with the result is saved ?: out\img\1687092983.0575006_145_2_suitcase
Saving all!
x1: 507 x2: 535 y1: 226 y2: 266
 	 The image with the result is saved ?: out\img\1687092983.057

pred i 0 tensor([[4.12856e+01, 7.92921e+01, 1.27373e+02, 1.70511e+02, 6.52546e-01, 2.80000e+01],
        [5.89752e-02, 9.41608e+00, 1.00045e+02, 2.11451e+02, 5.71076e-01, 0.00000e+00],
        [1.55774e+02, 8.58058e+00, 3.06561e+02, 1.02707e+02, 3.69545e-01, 5.70000e+01],
        [2.10773e+02, 1.15328e+01, 3.04299e+02, 1.02309e+02, 3.58450e-01, 6.20000e+01],
        [1.70623e+02, 9.22715e+01, 2.13342e+02, 1.36349e+02, 3.57767e-01, 2.60000e+01],
        [3.85914e+02, 1.31163e+02, 4.44540e+02, 2.07388e+02, 3.44316e-01, 5.80000e+01],
        [3.06796e+02, 1.14233e+02, 3.88378e+02, 1.93995e+02, 3.10671e-01, 5.60000e+01]])
save_path: out\stream2
x1: 409 x2: 518 y1: 140 y2: 247
 	 The image with the result is saved ?: out\img\1687092985.9994552_149_1_chair
Saving all!
x1: 515 x2: 593 y1: 163 y2: 265
 	 The image with the result is saved ?: out\img\1687092985.9994552_149_2_potted plant
Saving all!
x1: 227 x2: 284 y1: 111 y2: 170
 	 The image with the result is saved ?: out\img\1687092985.9994

TIMELINE: 1687092989.8416905 1687092989.0570676
I)img# 1 im0s# 1
II)img# 1 im0s# 1
pred i 0 tensor([[-1.82648e-01,  8.75245e+00,  1.33139e+02,  2.31557e+02,  8.26926e-01,  0.00000e+00],
        [ 3.06381e+02,  1.13126e+02,  3.89145e+02,  1.93843e+02,  5.26350e-01,  5.60000e+01],
        [ 2.09613e+02,  9.85411e+00,  3.04638e+02,  1.01601e+02,  4.75542e-01,  6.20000e+01],
        [ 1.20243e+02,  8.83741e+00,  1.86266e+02,  8.59379e+01,  4.49628e-01,  0.00000e+00],
        [ 2.10342e+02,  8.80677e+00,  3.06708e+02,  1.01355e+02,  2.94399e-01,  5.70000e+01]])
save_path: out\stream2
x1: 280 x2: 409 y1: 0 y2: 123
 	 The image with the result is saved ?: out\img\1687092989.8416905_154_1_couch
Saving all!
x1: 160 x2: 248 y1: 0 y2: 103
 	 The image with the result is saved ?: out\img\1687092989.8416905_154_2_person
Nose coordinates: (33.32491970062256, 3.7602957487106323)
Foot Left coordinates: (84.14802360534668, 115.55949020385742)
Foot Right coordinates: (60.12712860107422, 115.874631643295

KeyboardInterrupt: 