In [1]:
#!pip install deepface

In [2]:
#! git clone https://github.com/WongKinYiu/yolov7.git
#!pip install torchvision
#!pip install toch
#!pip install yoloface

In [3]:
import argparse
import time
from pathlib import Path

import numpy as np



import os
import glob
import cv2
import torch
import torch.backends.cudnn as cudnn
from numpy import random

from yoloface import face_analysis

from models.experimental import attempt_load
from utils.datasets import LoadStreams, LoadImages
from utils.general import check_img_size, check_requirements, check_imshow, non_max_suppression, apply_classifier, \
    scale_coords, xyxy2xywh, strip_optimizer, set_logging, increment_path
from utils.plots import plot_one_box
from utils.torch_utils import select_device, load_classifier, time_synchronized, TracedModel

import mediapipe as mp
mp_drawing = mp.solutions.drawing_utils
mp_drawing_styles = mp.solutions.drawing_styles
mp_pose = mp.solutions.pose

BG_COLOR = (192, 192, 192)

print("HOLA")

dir_cam1 = "cam2"
dir_cam2 = "floor"

myfolder= "test/scene5"

H2=np.load("H"+dir_cam1+"x"+dir_cam2+".npy")


def detect(save_img=True):
    
    os.makedirs("./out/"+myfolder+"/raw_"+dir_cam1+"/img/", exist_ok=True)
    files = glob.glob("./out/"+myfolder+"/raw_"+dir_cam1+"/img/*")
    for f in files:
        os.remove(f)

    os.makedirs("./out/"+myfolder+"/raw_"+dir_cam1+"/img3D/", exist_ok=True)
    files = glob.glob("./out/"+myfolder+"/raw_"+dir_cam1+"/img3D/*")
    for f in files:
        os.remove(f)
        
    os.makedirs("./out/"+myfolder+"/raw_"+dir_cam1+"/labels/", exist_ok=True)
    files = glob.glob("./out/"+myfolder+"/raw_"+dir_cam1+"/labels/*")
    for f in files:
        os.remove(f)        
    
    os.makedirs("./out/"+myfolder+"/raw_"+dir_cam1+"/foot2D/", exist_ok=True)
    files = glob.glob("./out/"+myfolder+"/raw_"+dir_cam1+"/foot2D/*")
    for f in files:
        os.remove(f)    
        
    os.makedirs("./out/"+myfolder+"/raw_"+dir_cam1+"/land3D/", exist_ok=True)
    files = glob.glob("./out/"+myfolder+"/raw_"+dir_cam1+"/land3D/*")
    for f in files:
        os.remove(f) 
    os.makedirs("./out/"+myfolder+"/raw_"+dir_cam1+"/faces/", exist_ok=True) 
    files = glob.glob("./out/"+myfolder+"/raw_"+dir_cam1+"/faces/*")
    for f in files:
        os.remove(f)
        
        
    file2d = open("./out/"+myfolder+"/raw_"+dir_cam1+"/foot2D/"+"tracking.txt", "w")
    file3d = open("./out/"+myfolder+"/raw_"+dir_cam1+"/land3D/"+"tracking.txt", "w")
        
    augment=False
    conf_thres=0.25
    iou_thres=0.45
    classes=None
    agnostic_nms=False
    save_conf=True
    save_txt=True
    #source='rtsp://Adetem:AuroraJavi@192.168.95.146:554/stream2'
    #source='rtsp://Adetem:AuroraJavi@192.168.1.20:554/stream2'
    source="./out/"+myfolder+"/"+dir_cam1+"/"
    #source='0'
    #source, weights, view_img, save_txt, imgsz, trace = opt.source, opt.weights, opt.view_img, opt.save_txt, opt.img_size, not opt.no_trace
    #save_img = not opt.nosave and not source.endswith('.txt')  # save inference images
    #webcam = source.isnumeric() or source.endswith('.txt') or source.lower().startswith(
    #    ('rtsp://', 'rtmp://', 'http://', 'https://'))
    imgsz=480
    webcam=True
    project="./out/"+myfolder
    name="raw_"+dir_cam1
    exist_ok=True
    
    # Directories
    #save_dir = Path(increment_path(Path(opt.project) / opt.name, exist_ok=opt.exist_ok))  # increment run
    #(save_dir / 'labels' if save_txt else save_dir).mkdir(parents=True, exist_ok=True)  # make dir
 
    save_dir = Path(increment_path(Path(project) / name, exist_ok=exist_ok))  # increment run
    (save_dir / 'labels' if save_txt else save_dir).mkdir(parents=True, exist_ok=True)  # make dir
    
    
    pose=mp_pose.Pose(  static_image_mode=True,model_complexity=2,enable_segmentation=True,min_detection_confidence=0.5)
    
    face=face_analysis()
    
    # Initialize
    #set_logging()
    device = select_device('')
    #half = device.type != 'cpu'  # half precision only supported on CUDA
    half = False
    # Load model
    model = attempt_load('yolov7.pt', map_location=device)  # load FP32 model
    stride = int(model.stride.max())  # model stride
    imgsz = check_img_size(imgsz, s=stride)  # check img_size

    #if trace:
    #model = TracedModel(model, device, opt.img_size)

    #if half:
    #    model.half()  # to FP16

    # Second-stage classifier


    # Set Dataloader
    #vid_path, vid_writer = None, None
    #if webcam:
    view_img = check_imshow()
    cudnn.benchmark = True  # set True to speed up constant image size inference
    #dataset = LoadStreams(source, img_size=imgsz, stride=stride)
    #else:
    dataset = LoadImages(source, img_size=imgsz, stride=stride)

    # Get names and colors
    names = model.module.names if hasattr(model, 'module') else model.names
    colors = [[random.randint(0, 255) for _ in range(3)] for _ in names]

    # Run inference
    if device.type != 'cpu':
        model(torch.zeros(1, 3, imgsz, imgsz).to(device).type_as(next(model.parameters())))  # run once
    old_img_w = old_img_h = imgsz
    old_img_b = 1



    for path, img, im0s, vid_cap in dataset:
        try:
            
            ts = path[path.rfind("\\")+1:path.rfind(".")]
            
            print("path:",path)
            print("TIMELINE:",ts)


            print("I)img#",len(img),"im0s#",len(im0s))
            #img=[img[0]]
            #im0s=[im0s[0]]
            
            aa=cv2.imread(path)
            aa=cv2.resize(aa, dsize=(640, 384), interpolation=cv2.INTER_CUBIC)
            print(aa)
            img=np.array([np.transpose(aa,(2, 0, 1))])
            im0s=np.array([cv2.imread(path)])
            
            print("II)img#",img.shape,"im0s#",type(img))
            img = torch.from_numpy(img).to(device)
            print("img.shape:",img.shape)
            
            #print(img)
            img = img.half() if half else img.float()  # uint8 to fp16/32
            img /= 255.0  # 0 - 255 to 0.0 - 1.0
            if img.ndimension() == 3:
                img = img.unsqueeze(0)

            # Inference
            t1 = time_synchronized()
            with torch.no_grad():   # Calculating gradients would cause a GPU memory leak
                pred = model(img, augment=augment)[0]
            t2 = time_synchronized()

            # Apply NMS
            pred = non_max_suppression(pred, conf_thres, iou_thres, classes=classes, agnostic=agnostic_nms)
            t3 = time_synchronized()

            # Process detections
            for i, det in enumerate(pred):  # detections per image
                p, s, im0, frame = path[i], '%g: ' % i, im0s[i].copy(), dataset.count
                im0=cv2.imread(path)
                
                print("pred i shape#",i, det,im0.shape)
                img2D = np.zeros((im0.shape[0], im0.shape[1], 3), dtype=np.uint8)
                img2D = cv2.rectangle(img2D, (0,0), (350,350), 255, 2)
                p = Path(p)  # to Path
                txt_path = str(save_dir / 'labels' / str(ts)) + (f'_{frame}')  # img.txt
                gn = torch.tensor(im0.shape)[[1, 0, 1, 0]]  # normalization gain whwh
                if len(det):
                    # Rescale boxes from img_size to im0 size
                    det[:, :4] = scale_coords(img.shape[2:], det[:, :4], im0.shape).round()

                    # Print results
                    for c in det[:, -1].unique():
                        n = (det[:, -1] == c).sum()  # detections per class
                        s += f"{n} {names[int(c)]}{'s' * (n > 1)}, "  # add to string

                    # Write results
                    indexP=0
                    for *xyxy, conf, cls in reversed(det):
                        indexP=indexP+1
                        if save_txt:  # Write to file
                            x1,x2,y1,y2=int(xyxy[0].item()),int(xyxy[2].item()),int(xyxy[1].item()),int(xyxy[3].item())
                            print("x1:",x1,"x2:",x2,"y1:",y1,"y2:",y2)
                            xywh = (xyxy2xywh(torch.tensor(xyxy).view(1, 4)) / gn).view(-1).tolist()  # normalized xywh
                            line = (cls, *xywh, conf)
                            im00 = im0s[i][y1:y2, x1:x2]
                            img_path = str(save_dir / 'img' / str(ts)) + (f'_{frame}')  # img.txt
                            img_path=img_path+"_"+str(indexP)+"_"+names[int(cls)]
                            print(f" \t The image with the result is saved ?: {img_path}", im0s.shape, im00.shape)
                            cv2.imwrite(img_path+ '.jpg', im00)
                    
                            with open(txt_path + '.txt', 'a') as f:
                                f.write(('%g ' * len(line)).rstrip() % line + '\n')
                                
                                
                            #head
                            if(cls==0):
                                try:
                                    box2,conf2=[],[]
                                    img2,box2,conf2=face.face_detection(frame_arr=im00,model='tiny')
                                    for iface,facebox in enumerate(box2):
                                        print("Box face:",facebox)
                                        im000 = im00[facebox[1]:facebox[1]+facebox[2], facebox[0]:facebox[0]+facebox[3]]
                                        img_path = str(save_dir / 'faces' / str(ts)) + (f'_{frame}')  # img.txt
                                        img_path=img_path+"_"+str(indexP)+"_"+names[int(cls)]+"_"+ str(iface)
                                        print(f" \t The face with the result is saved ?: {img_path}", im000.shape)
                                        cv2.imwrite(img_path+ '.jpg', im000)

                                except Exception as e:
                                    print("Bad ?",e)
                                    
                            #Pose 2D    
                            if(cls ==0):
                                results = pose.process(cv2.cvtColor(im00, cv2.COLOR_BGR2RGB))
                                image_height, image_width, _ = im00.shape
                                image_height0, image_width0, _ = im0.shape
                                
                                if not results.pose_landmarks:
                                     print("None 3D ")
                                else:
                                    print(
                                        f'Nose coordinates: ('
                                        f'{results.pose_landmarks.landmark[mp_pose.PoseLandmark.NOSE].x * image_width0}, '
                                        f'{results.pose_landmarks.landmark[mp_pose.PoseLandmark.NOSE].y * image_height0})'
                                    )
                                    print(
                                        f'Foot Left coordinates: ('
                                        f'{x1+results.pose_landmarks.landmark[mp_pose.PoseLandmark.LEFT_FOOT_INDEX].x * image_width}, '
                                        f'{y1+results.pose_landmarks.landmark[mp_pose.PoseLandmark.LEFT_FOOT_INDEX].y * image_height})'
                                    )
                                    print(
                                        f'Foot Right coordinates: ('
                                        f'{x1+results.pose_landmarks.landmark[mp_pose.PoseLandmark.RIGHT_FOOT_INDEX].x * image_width}, '
                                        f'{y1+results.pose_landmarks.landmark[mp_pose.PoseLandmark.RIGHT_FOOT_INDEX].y * image_height})'
                                    )
                                    
                                    
                                    
                                    #Foot location x 2D 
                                    sourcePoints=np.array([
                                            [[ x1+results.pose_landmarks.landmark[mp_pose.PoseLandmark.LEFT_FOOT_INDEX].x * image_width,
                                             y1+results.pose_landmarks.landmark[mp_pose.PoseLandmark.LEFT_FOOT_INDEX].y * image_height]],
                                            [[ x1+results.pose_landmarks.landmark[mp_pose.PoseLandmark.RIGHT_FOOT_INDEX].x * image_width,
                                             y1+results.pose_landmarks.landmark[mp_pose.PoseLandmark.RIGHT_FOOT_INDEX].y * image_height]]
                                        ])
                                    pts1 = sourcePoints.reshape(-1,1,2).astype(np.float32)
                                    #Multiplicamos por H los origenes para saber donde caen y comparamos con la real
                                    dst2 = cv2.perspectiveTransform(pts1, H2)
                                    img_path = str(save_dir / 'foot2D' / str(ts)) + (f'_{indexP}')  # img.txt
                                    f_land = open(img_path+".json", "w")

                                    # Plot 2D points
                                    
                                    
                                    
    
                                    for ix in range(0,len(dst2)):
                                        print(pts1[ix],"prediction ",dst2[ix][0])
                                        f_land.write(str(results.pose_landmarks.landmark[mp_pose.PoseLandmark.LEFT_FOOT_INDEX].visibility)
                                                     +"\t"+str(pts1[ix][0][0])
                                                     +"\t"+str(pts1[ix][0][1])
                                                     +"\t"+str(dst2[ix][0][0])
                                                     +"\t"+str(dst2[ix][0][1])
                                                     +"\n")
                                        center=(int(dst2[ix][0][0]*50),int(dst2[ix][0][1]*50))
                                        print("center",center)
                                        img2D = cv2.circle(img2D, center , 2, 255, -1)
                                        file2d.write(str(ts)+"_"+str(indexP)+"\t"+str(dst2[ix][0][0])+"\t"+str(dst2[ix][0][1])+"\n")
                                    f_land.close()
                                    
                                    annotated_image = im00.copy()
                                    # Draw segmentation on the image.
                                    # To improve segmentation around boundaries, consider applying a joint
                                    # bilateral filter to "results.segmentation_mask" with "image".
                                    condition = np.stack((results.segmentation_mask,) * 3, axis=-1) > 0.1
                                    bg_image = np.zeros(im00.shape, dtype=np.uint8)
                                    bg_image[:] = BG_COLOR
                                    annotated_image = np.where(condition, annotated_image, bg_image)
                                    print(" 3D A")
                                    # Draw pose landmarks on the image.
                                    mp_drawing.draw_landmarks(
                                        annotated_image,
                                        results.pose_landmarks,
                                        mp_pose.POSE_CONNECTIONS,
                                        landmark_drawing_spec=mp_drawing_styles.get_default_pose_landmarks_style())
                                    print(" 3D B")
                                    img_path = str(save_dir / 'img3D' / str(ts)) + (f'_{indexP}')  # img.txt
                                    #img_path=img_path+"_"+str(i)+"_"+names[int(cls)]
                                    print(f" \t The image with the result is saved ?: {img_path}")
                                    cv2.imwrite(img_path+ '.jpg', annotated_image)

                                    print(" 3D C")
                                    img_path = str(save_dir / 'land3D' / str(ts)) + (f'_{indexP}')  # img.txt
                                    f_land = open(img_path+".json", "w")
                                    file3d.write(str(ts)+"_"+str(indexP))
                                    for land in results.pose_world_landmarks.landmark:
                                        #print("\t land:",land.x)
                                        f_land.write(str(land.x)+"\t"+str(land.y)+"\t"+str(land.z)+"\t"+str(land.visibility)+"\n")
                                        file3d.write("\t"+str(land.x)+"\t"+str(land.y)+"\t"+str(land.z)+"\t"+str(land.visibility))
                                    file3d.write("\n")
                                    f_land.close()
                                    

                                
                        print("Saving all!")
                        if save_img or view_img:  # Add bbox to image
                            label = f'{names[int(cls)]} {conf:.2f}'
                            plot_one_box(xyxy, im0, label=label, color=colors[int(cls)], line_thickness=1)

                # Print time (inference + NMS)
                #print(f'{s}Done. ({(1E3 * (t2 - t1)):.1f}ms) Inference, ({(1E3 * (t3 - t2)):.1f}ms) NMS')

                # Stream results
                if view_img:
                    print("SHAPES:",im0.shape,img2D.shape)
                    hor = np.concatenate((im0, img2D), axis=1)
                    cv2.imshow(str(p), hor)
                    cv2.waitKey(1)  # 1 millisecond

                # Save results (image with detections)
                if save_img:
                    img_path = str(save_dir / 'img' / str(ts)) + ('' if dataset.mode == 'image' else f'_{frame}')  # img.txt
                
                    print(f" The image with the result is saved ?: {img_path}")
                    cv2.imwrite(img_path+ '.jpg', im0)
        except Exception as e:
            print(e)

    if save_txt or save_img:
        s = f"\n{len(list(save_dir.glob('labels/*.txt')))} labels saved to {save_dir / 'labels'}" if save_txt else ''
        #print(f"Results saved to {save_dir}{s}")

    print("Done")
    file2d.close()
    file3d.close()
    cv2.destroyAllWindows()


if __name__ == '__main__':
    print("hola")
    parser = argparse.ArgumentParser()
    parser.add_argument('--weights', nargs='+', type=str, default='yolov7.pt', help='model.pt path(s)')
    parser.add_argument('--source', type=str, default='inference/images', help='source')  # file/folder, 0 for webcam
    parser.add_argument('--img-size', type=int, default=640, help='inference size (pixels)')
    parser.add_argument('--conf-thres', type=float, default=0.25, help='object confidence threshold')
    parser.add_argument('--iou-thres', type=float, default=0.45, help='IOU threshold for NMS')
    parser.add_argument('--device', default='', help='cuda device, i.e. 0 or 0,1,2,3 or cpu')
    parser.add_argument('--view-img', action='store_true', help='display results')
    parser.add_argument('--save-txt', action='store_true', help='save results to *.txt')
    parser.add_argument('--save-conf', action='store_true', help='save confidences in --save-txt labels')
    parser.add_argument('--nosave', action='store_true', help='do not save images/videos')
    parser.add_argument('--classes', nargs='+', type=int, help='filter by class: --class 0, or --class 0 2 3')
    parser.add_argument('--agnostic-nms', action='store_true', help='class-agnostic NMS')
    parser.add_argument('--augment', action='store_true', help='augmented inference')
    parser.add_argument('--update', action='store_true', help='update all models')
    parser.add_argument('--project', default='runs/detect', help='save results to project/name')
    parser.add_argument('--name', default='exp', help='save results to project/name')
    parser.add_argument('--exist-ok', action='store_true', help='existing project/name ok, do not increment')
    parser.add_argument('--no-trace', action='store_true', help='don`t trace model')
    print("hola")
    #opt = parser.parse_args()
    #print(opt)
    print("hola")
    #check_requirements(exclude=('pycocotools', 'thop'))

    with torch.no_grad():
        print("hola")
        #if opt.update:  # update all models (to fix SourceChangeWarning)
        #    for opt.weights in ['yolov7.pt']:
        #        detect()
        #        strip_optimizer(opt.weights)
        #else:
        detect()


HOLA
hola
hola
hola
hola
yolov3-tiny_face.weights:: status : file already exists
yolov3_tiny_face.cfg:: status : file already exists
face_detection.weights:: status : file already exists
face_detection.cfg:: status : file already exists
Fusing layers... 
RepConv.fuse_repvgg_block
RepConv.fuse_repvgg_block
RepConv.fuse_repvgg_block
path: C:\Users\javie\Documents\GitHub\Camera2VirtualUCAmI\yolov7\out\test\scene5\cam2\1687446214.png
TIMELINE: 1687446214
I)img# 3 im0s# 360
[[[105 105 105]
  [125 125 125]
  [124 124 124]
  ...
  [233 230 229]
  [233 230 229]
  [233 230 229]]

 [[121 121 121]
  [139 139 139]
  [137 137 137]
  ...
  [233 230 229]
  [233 230 229]
  [233 230 229]]

 [[109 109 109]
  [131 131 131]
  [  0   0   0]
  ...
  [233 230 229]
  [233 230 229]
  [233 230 229]]

 ...

 [[ 77  91 123]
  [ 77  91 123]
  [ 77  91 123]
  ...
  [164 166 168]
  [164 166 168]
  [164 166 168]]

 [[ 75  89 121]
  [ 75  89 121]
  [ 75  89 121]
  ...
  [164 166 168]
  [164 166 168]
  [164 166 168]]



C:\Users\javie\anaconda3\lib\site-packages\torch\functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\TensorShape.cpp:3484.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]


pred i shape# 0 tensor([[5.22556e+02, 1.13122e+02, 6.18405e+02, 2.99528e+02, 9.44950e-01, 0.00000e+00],
        [3.89379e+02, 8.25453e+01, 4.43322e+02, 1.53585e+02, 8.86270e-01, 0.00000e+00],
        [3.53781e+02, 1.27643e+02, 4.06463e+02, 1.67972e+02, 8.38353e-01, 6.30000e+01],
        [1.25440e+02, 9.35096e+01, 1.63085e+02, 1.44777e+02, 8.04040e-01, 5.60000e+01],
        [6.03594e+02, 2.40973e+02, 6.39907e+02, 3.75813e+02, 6.09150e-01, 5.60000e+01],
        [4.33534e+02, 1.07743e+02, 4.63744e+02, 1.55596e+02, 5.52282e-01, 5.60000e+01],
        [3.58112e+01, 1.42151e+02, 7.78873e+01, 1.97232e+02, 3.62432e-01, 2.80000e+01],
        [8.06519e+01, 1.29204e+02, 1.20470e+02, 1.66531e+02, 3.47317e-01, 2.60000e+01],
        [8.08289e+01, 1.29156e+02, 1.20555e+02, 1.65496e+02, 3.35293e-01, 2.80000e+01],
        [4.36656e+02, 1.53918e+02, 4.48466e+02, 1.70917e+02, 3.13111e-01, 4.10000e+01],
        [6.17317e+01, 1.25422e+02, 2.47233e+02, 2.87973e+02, 2.78498e-01, 6.00000e+01]]) (360, 640, 3)
x

Nose coordinates: (524.9124145507812, 63.60838830471039)
Foot Left coordinates: (543.4936919212341, 251.61929094791412)
Foot Right coordinates: (561.597282409668, 273.47666478157043)
[[     543.49      251.62]] prediction  [     1.2618       1.877]
center (63, 93)
[[      561.6      273.48]] prediction  [     1.4801      1.9323]
center (74, 96)
 3D A
 3D B
 	 The image with the result is saved ?: out\test\scene5\raw_cam2\img3D\1687446215_11
 3D C
Saving all!
SHAPES: (360, 640, 3) (360, 640, 3)
 The image with the result is saved ?: out\test\scene5\raw_cam2\img\1687446215
path: C:\Users\javie\Documents\GitHub\Camera2VirtualUCAmI\yolov7\out\test\scene5\cam2\1687446216.png
TIMELINE: 1687446216
I)img# 3 im0s# 360
[[[116 116 116]
  [131 131 131]
  [118 118 118]
  ...
  [235 232 226]
  [235 232 226]
  [235 232 226]]

 [[131 131 131]
  [144 144 144]
  [131 131 131]
  ...
  [235 232 226]
  [235 232 226]
  [235 232 226]]

 [[118 118 118]
  [136 136 136]
  [  0   0   0]
  ...
  [235 232 226]
  [

Box face: [18, 8, 25, 17]
 	 The face with the result is saved ?: out\test\scene5\raw_cam2\faces\1687446217_4_12_person_0 (25, 17, 3)
Nose coordinates: (275.42842864990234, 114.91821527481079)
Foot Left coordinates: (413.0137266218662, 240.15824627876282)
Foot Right coordinates: (401.3830521404743, 237.16674280166626)
[[     413.01      240.16]] prediction  [    0.99119      1.8405]
center (49, 92)
[[     401.38      237.17]] prediction  [     0.9564      1.8337]
center (47, 91)
 3D A
 3D B
 	 The image with the result is saved ?: out\test\scene5\raw_cam2\img3D\1687446217_12
 3D C
Saving all!
x1: 523 x2: 617 y1: 102 y2: 288
 	 The image with the result is saved ?: out\test\scene5\raw_cam2\img\1687446217_4_13_person (1, 360, 640, 3) (186, 94, 3)
Nose coordinates: (539.0401458740234, 62.00415372848511)
Foot Left coordinates: (536.6189592182636, 251.84643137454987)
Foot Right coordinates: (560.6506922245026, 273.42995846271515)
[[     536.62      251.85]] prediction  [     1.2536      1.8

Nose coordinates: (523.0084609985352, 62.849414348602295)
Foot Left coordinates: (538.5521988868713, 252.02270871400833)
Foot Right coordinates: (560.8771257400513, 273.6546530723572)
[[     538.55      252.02]] prediction  [     1.2577      1.8774]
center (62, 93)
[[     560.88      273.65]] prediction  [     1.4808      1.9328]
center (74, 96)
 3D A
 3D B
 	 The image with the result is saved ?: out\test\scene5\raw_cam2\img3D\1687446219_14
 3D C
Saving all!
SHAPES: (360, 640, 3) (360, 640, 3)
 The image with the result is saved ?: out\test\scene5\raw_cam2\img\1687446219
path: C:\Users\javie\Documents\GitHub\Camera2VirtualUCAmI\yolov7\out\test\scene5\cam2\1687446220.png
TIMELINE: 1687446220
I)img# 3 im0s# 360
[[[116 116 116]
  [131 131 131]
  [118 118 118]
  ...
  [234 231 230]
  [234 231 230]
  [234 231 230]]

 [[131 131 131]
  [144 144 144]
  [131 131 131]
  ...
  [234 231 230]
  [234 231 230]
  [234 231 230]]

 [[118 118 118]
  [136 136 136]
  [  0   0   0]
  ...
  [234 231 230]
  

Nose coordinates: (528.0382919311523, 62.7291601896286)
Foot Left coordinates: (539.6653686761856, 250.54839593172073)
Foot Right coordinates: (561.0783885717392, 273.1685841679573)
[[     539.67      250.55]] prediction  [     1.2483      1.8744]
center (62, 93)
[[     561.08      273.17]] prediction  [     1.4761      1.9314]
center (73, 96)
 3D A
 3D B
 	 The image with the result is saved ?: out\test\scene5\raw_cam2\img3D\1687446221_13
 3D C
Saving all!
SHAPES: (360, 640, 3) (360, 640, 3)
 The image with the result is saved ?: out\test\scene5\raw_cam2\img\1687446221
path: C:\Users\javie\Documents\GitHub\Camera2VirtualUCAmI\yolov7\out\test\scene5\cam2\1687446222.png
TIMELINE: 1687446222
I)img# 3 im0s# 360
[[[116 116 116]
  [131 131 131]
  [118 118 118]
  ...
  [236 231 230]
  [236 231 230]
  [236 231 230]]

 [[131 131 131]
  [144 144 144]
  [131 131 131]
  ...
  [236 231 230]
  [236 231 230]
  [236 231 230]]

 [[118 118 118]
  [136 136 136]
  [  0   0   0]
  ...
  [236 231 230]
  [2

Box face: [25, 5, 30, 15]
 	 The face with the result is saved ?: out\test\scene5\raw_cam2\faces\1687446223_10_5_person_0 (30, 15, 3)
Nose coordinates: (330.41160583496094, 47.25136041641235)
Foot Left coordinates: (397.50757521390915, 190.80504035949707)
Foot Right coordinates: (377.60483652353287, 192.46021842956543)
[[     397.51      190.81]] prediction  [    0.74992      1.7669]
center (37, 88)
[[      377.6      192.46]] prediction  [    0.73001      1.7666]
center (36, 88)
 3D A
 3D B
 	 The image with the result is saved ?: out\test\scene5\raw_cam2\img3D\1687446223_5
 3D C
Saving all!
x1: 354 x2: 406 y1: 115 y2: 156
 	 The image with the result is saved ?: out\test\scene5\raw_cam2\img\1687446223_10_6_laptop (1, 360, 640, 3) (41, 52, 3)
Saving all!
x1: 125 x2: 163 y1: 81 y2: 133
 	 The image with the result is saved ?: out\test\scene5\raw_cam2\img\1687446223_10_7_chair (1, 360, 640, 3) (52, 38, 3)
Saving all!
x1: 401 x2: 516 y1: 58 y2: 316
 	 The image with the result is saved ?

Box face: [6, 10, 44, 24]
 	 The face with the result is saved ?: out\test\scene5\raw_cam2\faces\1687446225_12_5_person_0 (44, 24, 3)
Nose coordinates: (52.184715270996094, 52.865331172943115)
Foot Left coordinates: (110.6212306022644, 351.5455246567726)
Foot Right coordinates: (32.55593083798885, 336.19735980033875)
[[     110.62      351.55]] prediction  [     1.8844      2.6981]
center (94, 134)
[[     32.556       336.2]] prediction  [    0.89831      2.3657]
center (44, 118)
 3D A
 3D B
 	 The image with the result is saved ?: out\test\scene5\raw_cam2\img3D\1687446225_5
 3D C
Saving all!
SHAPES: (360, 640, 3) (360, 640, 3)
 The image with the result is saved ?: out\test\scene5\raw_cam2\img\1687446225
path: C:\Users\javie\Documents\GitHub\Camera2VirtualUCAmI\yolov7\out\test\scene5\cam2\1687446226.png
TIMELINE: 1687446226
I)img# 3 im0s# 360
[[[116 116 116]
  [131 131 131]
  [118 118 118]
  ...
  [227 225 221]
  [227 225 221]
  [227 225 221]]

 [[131 131 131]
  [144 144 144]
  [131 1

Saving all!
x1: 125 x2: 163 y1: 81 y2: 132
 	 The image with the result is saved ?: out\test\scene5\raw_cam2\img\1687446227_14_9_tv (1, 360, 640, 3) (51, 38, 3)
Saving all!
x1: 371 x2: 419 y1: 122 y2: 156
 	 The image with the result is saved ?: out\test\scene5\raw_cam2\img\1687446227_14_10_laptop (1, 360, 640, 3) (34, 48, 3)
Saving all!
SHAPES: (360, 640, 3) (360, 640, 3)
 The image with the result is saved ?: out\test\scene5\raw_cam2\img\1687446227
path: C:\Users\javie\Documents\GitHub\Camera2VirtualUCAmI\yolov7\out\test\scene5\cam2\1687446228.png
TIMELINE: 1687446228
I)img# 3 im0s# 360
[[[105 105 105]
  [125 125 125]
  [124 124 124]
  ...
  [225 222 221]
  [225 222 221]
  [225 222 221]]

 [[121 121 121]
  [139 139 139]
  [137 137 137]
  ...
  [225 222 221]
  [225 222 221]
  [225 222 221]]

 [[109 109 109]
  [131 131 131]
  [  0   0   0]
  ...
  [225 222 221]
  [225 222 221]
  [225 222 221]]

 ...

 [[ 74  88 120]
  [ 73  87 119]
  [ 72  86 118]
  ...
  [160 162 164]
  [160 162 164]


pred i shape# 0 tensor([[1.25359e+02, 9.34449e+01, 1.63366e+02, 1.44933e+02, 6.48271e-01, 5.60000e+01],
        [3.66657e+02, 1.32903e+02, 4.19757e+02, 1.67474e+02, 5.72530e-01, 6.30000e+01],
        [1.25141e+02, 9.32895e+01, 1.63192e+02, 1.44377e+02, 4.87590e-01, 6.20000e+01],
        [3.65011e+02, 7.92400e+01, 4.20560e+02, 1.61496e+02, 4.53274e-01, 0.00000e+00],
        [6.04346e+02, 2.41303e+02, 6.39809e+02, 3.76383e+02, 4.18965e-01, 5.60000e+01],
        [8.05494e+01, 1.29002e+02, 1.20872e+02, 1.65991e+02, 3.93531e-01, 2.60000e+01],
        [3.52354e+01, 1.41878e+02, 7.76387e+01, 1.91301e+02, 3.09043e-01, 2.80000e+01],
        [8.07475e+01, 1.28958e+02, 1.20897e+02, 1.65172e+02, 2.59972e-01, 2.80000e+01]]) (360, 640, 3)
x1: 81 x2: 121 y1: 117 y2: 153
 	 The image with the result is saved ?: out\test\scene5\raw_cam2\img\1687446230_17_1_suitcase (1, 360, 640, 3) (36, 40, 3)
Saving all!
x1: 35 x2: 78 y1: 130 y2: 179
 	 The image with the result is saved ?: out\test\scene5\raw_cam2\im

Box face: [26, 11, 44, 27]
 	 The face with the result is saved ?: out\test\scene5\raw_cam2\faces\1687446232_19_8_person_0 (44, 27, 3)
Nose coordinates: (229.95975494384766, 54.21846270561218)
Foot Left coordinates: (170.0166490674019, 320.4648551940918)
Foot Right coordinates: (79.21251130104065, 345.00795698165894)
[[     170.02      320.46]] prediction  [     1.2179      2.1397]
center (60, 106)
[[     79.213      345.01]] prediction  [     1.4136      2.5343]
center (70, 126)
 3D A
 3D B
 	 The image with the result is saved ?: out\test\scene5\raw_cam2\img3D\1687446232_8
 3D C
Saving all!
SHAPES: (360, 640, 3) (360, 640, 3)
 The image with the result is saved ?: out\test\scene5\raw_cam2\img\1687446232
path: C:\Users\javie\Documents\GitHub\Camera2VirtualUCAmI\yolov7\out\test\scene5\cam2\1687446233.png
TIMELINE: 1687446233
I)img# 3 im0s# 360
[[[105 105 105]
  [125 125 125]
  [124 124 124]
  ...
  [226 223 222]
  [226 223 222]
  [226 223 222]]

 [[121 121 121]
  [139 139 139]
  [137 1

pred i shape# 0 tensor([[5.21436e+02, 1.43482e+02, 6.19899e+02, 3.00125e+02, 9.10796e-01, 0.00000e+00],
        [6.10177e+02, 1.58984e+02, 6.40049e+02, 2.06828e+02, 8.37784e-01, 6.30000e+01],
        [6.04666e+02, 2.80757e+02, 6.40055e+02, 3.77644e+02, 6.12989e-01, 5.60000e+01],
        [1.25531e+02, 9.33979e+01, 1.63353e+02, 1.45175e+02, 6.07488e-01, 5.60000e+01],
        [1.25197e+02, 9.32623e+01, 1.63258e+02, 1.44698e+02, 5.63079e-01, 6.20000e+01],
        [3.67077e+02, 1.33273e+02, 4.18589e+02, 1.67312e+02, 5.00361e-01, 6.30000e+01],
        [8.07309e+01, 1.29295e+02, 1.20671e+02, 1.65191e+02, 4.62650e-01, 2.80000e+01],
        [3.64043e+02, 7.97523e+01, 4.34744e+02, 1.61743e+02, 4.45872e-01, 0.00000e+00],
        [8.05688e+01, 1.28942e+02, 1.20159e+02, 1.66506e+02, 3.33512e-01, 2.60000e+01],
        [3.57139e+01, 1.42161e+02, 7.77652e+01, 1.96629e+02, 3.19285e-01, 2.80000e+01],
        [3.65851e+02, 7.93293e+01, 4.38814e+02, 2.53437e+02, 2.84532e-01, 0.00000e+00],
        [6.08754

Nose coordinates: (392.0363998413086, 67.17351078987122)
Foot Left coordinates: (531.5420100092888, 268.395505130291)
Foot Right coordinates: (549.0182826817036, 274.0069771409035)
[[     531.54       268.4]] prediction  [     1.3842      1.9158]
center (69, 95)
[[     549.02      274.01]] prediction  [     1.4659      1.9328]
center (73, 96)
 3D A
 3D B
 	 The image with the result is saved ?: out\test\scene5\raw_cam2\img3D\1687446236_12
 3D C
Saving all!
SHAPES: (360, 640, 3) (360, 640, 3)
 The image with the result is saved ?: out\test\scene5\raw_cam2\img\1687446236
path: C:\Users\javie\Documents\GitHub\Camera2VirtualUCAmI\yolov7\out\test\scene5\cam2\1687446237.png
TIMELINE: 1687446237
I)img# 3 im0s# 360
[[[105 105 105]
  [125 125 125]
  [124 124 124]
  ...
  [227 223 219]
  [227 223 219]
  [227 223 219]]

 [[121 121 121]
  [139 139 139]
  [137 137 137]
  ...
  [227 223 219]
  [227 223 219]
  [227 223 219]]

 [[109 109 109]
  [131 131 131]
  [  0   0   0]
  ...
  [227 223 219]
  [22

Nose coordinates: (375.9812927246094, 71.20011270046234)
Foot Left coordinates: (370.33878177404404, 142.43374428153038)
Foot Right coordinates: (369.7925814092159, 141.2820037305355)
[[     370.34      142.43]] prediction  [    0.58653      1.7198]
center (29, 85)
[[     369.79      141.28]] prediction  [    0.58346      1.7189]
center (29, 85)
 3D A
 3D B
 	 The image with the result is saved ?: out\test\scene5\raw_cam2\img3D\1687446238_9
 3D C
Saving all!
x1: 126 x2: 163 y1: 81 y2: 133
 	 The image with the result is saved ?: out\test\scene5\raw_cam2\img\1687446238_25_10_chair (1, 360, 640, 3) (52, 37, 3)
Saving all!
x1: 604 x2: 640 y1: 229 y2: 360
 	 The image with the result is saved ?: out\test\scene5\raw_cam2\img\1687446238_25_11_chair (1, 360, 640, 3) (131, 36, 3)
Saving all!
x1: 125 x2: 163 y1: 81 y2: 133
 	 The image with the result is saved ?: out\test\scene5\raw_cam2\img\1687446238_25_12_tv (1, 360, 640, 3) (52, 38, 3)
Saving all!
x1: 371 x2: 420 y1: 121 y2: 156
 	 The imag

pred i shape# 0 tensor([[5.20698e+02, 1.45538e+02, 6.18766e+02, 3.00217e+02, 8.99897e-01, 0.00000e+00],
        [1.25160e+02, 9.31201e+01, 1.62802e+02, 1.44465e+02, 7.82712e-01, 6.20000e+01],
        [6.10263e+02, 1.59048e+02, 6.39861e+02, 2.06720e+02, 5.95448e-01, 6.30000e+01],
        [3.70553e+02, 1.32795e+02, 4.18758e+02, 1.67878e+02, 5.90854e-01, 6.30000e+01],
        [6.04950e+02, 2.40916e+02, 6.39916e+02, 3.75942e+02, 5.74078e-01, 5.60000e+01],
        [3.63353e+02, 8.08987e+01, 4.22315e+02, 1.58122e+02, 5.32524e-01, 0.00000e+00],
        [8.05223e+01, 1.28956e+02, 1.20767e+02, 1.65397e+02, 4.80263e-01, 2.60000e+01],
        [3.62043e+02, 8.15876e+01, 4.24650e+02, 2.45533e+02, 3.60645e-01, 0.00000e+00],
        [3.53277e+01, 1.42176e+02, 7.78343e+01, 1.89830e+02, 2.80083e-01, 2.40000e+01],
        [8.06138e+01, 1.28942e+02, 1.20742e+02, 1.64436e+02, 2.79308e-01, 2.80000e+01],
        [3.53955e+01, 1.42212e+02, 7.78639e+01, 1.90865e+02, 2.69869e-01, 2.80000e+01],
        [5.21665

Nose coordinates: (378.6754608154297, 66.31545066833496)
Foot Left coordinates: (539.7917819023132, 268.4974687099457)
Foot Right coordinates: (549.9853950738907, 273.71395486593246)
[[     539.79       268.5]] prediction  [      1.398      1.9168]
center (69, 95)
[[     549.99      273.71]] prediction  [     1.4645       1.932]
center (73, 96)
 3D A
 3D B
 	 The image with the result is saved ?: out\test\scene5\raw_cam2\img3D\1687446241_10
 3D C
Saving all!
SHAPES: (360, 640, 3) (360, 640, 3)
 The image with the result is saved ?: out\test\scene5\raw_cam2\img\1687446241
path: C:\Users\javie\Documents\GitHub\Camera2VirtualUCAmI\yolov7\out\test\scene5\cam2\1687446242.png
TIMELINE: 1687446242
I)img# 3 im0s# 360
[[[105 105 105]
  [125 125 125]
  [124 124 124]
  ...
  [225 224 218]
  [225 224 218]
  [225 224 218]]

 [[121 121 121]
  [139 139 139]
  [137 137 137]
  ...
  [225 224 218]
  [225 224 218]
  [225 224 218]]

 [[109 109 109]
  [131 131 131]
  [  0   0   0]
  ...
  [225 224 218]
  [

pred i shape# 0 tensor([[5.20388e+02, 1.45072e+02, 6.19748e+02, 2.99597e+02, 8.93124e-01, 0.00000e+00],
        [1.25467e+02, 9.35317e+01, 1.63073e+02, 1.44672e+02, 7.58921e-01, 5.60000e+01],
        [6.04773e+02, 2.40379e+02, 6.39843e+02, 3.76243e+02, 6.33636e-01, 5.60000e+01],
        [3.68568e+02, 1.32099e+02, 4.19914e+02, 1.68157e+02, 4.34509e-01, 6.30000e+01],
        [8.05790e+01, 1.29368e+02, 1.19999e+02, 1.67005e+02, 4.27995e-01, 2.60000e+01],
        [3.55494e+01, 1.42331e+02, 7.74829e+01, 1.97596e+02, 4.01141e-01, 2.80000e+01],
        [6.09508e+02, 1.58868e+02, 6.39961e+02, 2.07107e+02, 3.86488e-01, 6.30000e+01],
        [3.68736e+02, 1.32771e+02, 4.20511e+02, 1.67638e+02, 3.71301e-01, 2.60000e+01],
        [5.20672e+02, 2.41192e+02, 5.91229e+02, 3.01485e+02, 3.56222e-01, 5.60000e+01],
        [6.14346e+01, 1.24197e+02, 2.46570e+02, 2.88335e+02, 2.90450e-01, 6.00000e+01],
        [6.11808e+01, 1.22838e+02, 2.46709e+02, 2.86814e+02, 2.51950e-01, 5.90000e+01]]) (360, 640, 3)
x

pred i shape# 0 tensor([[5.20179e+02, 1.45485e+02, 6.18746e+02, 2.99831e+02, 9.11614e-01, 0.00000e+00],
        [6.04630e+02, 2.40821e+02, 6.39885e+02, 3.76381e+02, 6.26701e-01, 5.60000e+01],
        [3.70318e+02, 1.32509e+02, 4.19409e+02, 1.67815e+02, 6.23380e-01, 6.30000e+01],
        [1.25141e+02, 9.32476e+01, 1.63143e+02, 1.44831e+02, 5.72133e-01, 6.20000e+01],
        [6.09855e+02, 1.58830e+02, 6.39953e+02, 2.06747e+02, 5.12746e-01, 6.30000e+01],
        [1.25526e+02, 9.33652e+01, 1.63130e+02, 1.45043e+02, 4.30746e-01, 5.60000e+01],
        [3.66341e+02, 8.11402e+01, 4.24712e+02, 2.46956e+02, 4.18085e-01, 0.00000e+00],
        [3.62022e+02, 1.06611e+02, 3.84781e+02, 1.55646e+02, 3.46547e-01, 2.60000e+01],
        [3.56966e+01, 1.41404e+02, 7.78836e+01, 1.95540e+02, 3.39452e-01, 2.80000e+01],
        [8.06154e+01, 1.28985e+02, 1.20945e+02, 1.65280e+02, 2.85940e-01, 2.80000e+01]]) (360, 640, 3)
x1: 81 x2: 121 y1: 117 y2: 153
 	 The image with the result is saved ?: out\test\scene5\r

Nose coordinates: (386.7354202270508, 62.215447425842285)
Foot Left coordinates: (543.0882275104523, 272.1712466478348)
Foot Right coordinates: (549.8532538414001, 273.04707729816437)
[[     543.09      272.17]] prediction  [     1.4383      1.9271]
center (71, 96)
[[     549.85      273.05]] prediction  [     1.4576      1.9302]
center (72, 96)
 3D A
 3D B
 	 The image with the result is saved ?: out\test\scene5\raw_cam2\img3D\1687446247_13
 3D C
Saving all!
SHAPES: (360, 640, 3) (360, 640, 3)
 The image with the result is saved ?: out\test\scene5\raw_cam2\img\1687446247
path: C:\Users\javie\Documents\GitHub\Camera2VirtualUCAmI\yolov7\out\test\scene5\cam2\1687446248.png
TIMELINE: 1687446248
I)img# 3 im0s# 360
[[[105 105 105]
  [125 125 125]
  [124 124 124]
  ...
  [225 224 218]
  [225 224 218]
  [225 224 218]]

 [[121 121 121]
  [139 139 139]
  [137 137 137]
  ...
  [225 224 218]
  [225 224 218]
  [225 224 218]]

 [[109 109 109]
  [131 131 131]
  [  0   0   0]
  ...
  [225 224 218]
  

Box face: [28, 17, 23, 15]
 	 The face with the result is saved ?: out\test\scene5\raw_cam2\faces\1687446249_36_6_person_0 (23, 15, 3)
Nose coordinates: (327.66536712646484, 65.57364821434021)
Foot Left coordinates: (408.4269301891327, 173.2118348479271)
Foot Right coordinates: (390.66479513049126, 175.63800019025803)
[[     408.43      173.21]] prediction  [    0.70766      1.7498]
center (35, 87)
[[     390.66      175.64]] prediction  [     0.6936      1.7503]
center (34, 87)
 3D A
 3D B
 	 The image with the result is saved ?: out\test\scene5\raw_cam2\img3D\1687446249_6
 3D C
Saving all!
x1: 125 x2: 163 y1: 81 y2: 133
 	 The image with the result is saved ?: out\test\scene5\raw_cam2\img\1687446249_36_7_tv (1, 360, 640, 3) (52, 38, 3)
Saving all!
x1: 609 x2: 640 y1: 147 y2: 195
 	 The image with the result is saved ?: out\test\scene5\raw_cam2\img\1687446249_36_8_laptop (1, 360, 640, 3) (48, 31, 3)
Saving all!
x1: 81 x2: 121 y1: 117 y2: 152
 	 The image with the result is saved ?: ou

pred i shape# 0 tensor([[5.20241e+02, 1.45367e+02, 6.16933e+02, 3.00946e+02, 9.12969e-01, 0.00000e+00],
        [6.04802e+02, 2.40315e+02, 6.39850e+02, 3.76698e+02, 7.14084e-01, 5.60000e+01],
        [1.25489e+02, 9.33078e+01, 1.63298e+02, 1.44981e+02, 6.65825e-01, 5.60000e+01],
        [8.06879e+01, 1.29178e+02, 1.20811e+02, 1.64353e+02, 6.37175e-01, 2.80000e+01],
        [6.09271e+02, 1.59333e+02, 6.39960e+02, 2.06722e+02, 5.63209e-01, 6.30000e+01],
        [1.25173e+02, 9.32628e+01, 1.63079e+02, 1.44639e+02, 5.04464e-01, 6.20000e+01],
        [3.68902e+02, 7.48487e+01, 4.38965e+02, 2.49226e+02, 4.99629e-01, 0.00000e+00],
        [3.61712e+02, 1.06771e+02, 3.83513e+02, 1.55236e+02, 4.17624e-01, 2.60000e+01],
        [3.70936e+02, 1.32881e+02, 4.19369e+02, 1.67724e+02, 4.03717e-01, 6.30000e+01],
        [3.70931e+02, 1.32581e+02, 4.19972e+02, 1.67150e+02, 3.71404e-01, 2.60000e+01],
        [3.56592e+01, 1.41924e+02, 7.77548e+01, 1.91042e+02, 3.64758e-01, 2.80000e+01],
        [3.67204

Nose coordinates: (397.4360656738281, 61.12100958824158)
Foot Left coordinates: (544.3693390488625, 274.4961664676666)
Foot Right coordinates: (550.6746279001236, 272.3936200141907)
[[     544.37       274.5]] prediction  [     1.4636      1.9338]
center (73, 96)
[[     550.67      272.39]] prediction  [     1.4523      1.9284]
center (72, 96)
 3D A
 3D B
 	 The image with the result is saved ?: out\test\scene5\raw_cam2\img3D\1687446255_11
 3D C
Saving all!
SHAPES: (360, 640, 3) (360, 640, 3)
 The image with the result is saved ?: out\test\scene5\raw_cam2\img\1687446255
path: C:\Users\javie\Documents\GitHub\Camera2VirtualUCAmI\yolov7\out\test\scene5\cam2\1687446256.png
TIMELINE: 1687446256
I)img# 3 im0s# 360
[[[105 105 105]
  [125 125 125]
  [124 124 124]
  ...
  [227 224 218]
  [227 224 218]
  [227 224 218]]

 [[121 121 121]
  [139 139 139]
  [137 137 137]
  ...
  [227 224 218]
  [227 224 218]
  [227 224 218]]

 [[109 109 109]
  [131 131 131]
  [  0   0   0]
  ...
  [227 224 218]
  [2

Nose coordinates: (395.10406494140625, 62.31042981147766)
Foot Left coordinates: (546.4111998677254, 275.4668264389038)
Foot Right coordinates: (551.760698646307, 272.80710059404373)
[[     546.41      275.47]] prediction  [     1.4768      1.9368]
center (73, 96)
[[     551.76      272.81]] prediction  [     1.4581      1.9296]
center (72, 96)
 3D A
 3D B
 	 The image with the result is saved ?: out\test\scene5\raw_cam2\img3D\1687446257_11
 3D C
Saving all!
SHAPES: (360, 640, 3) (360, 640, 3)
 The image with the result is saved ?: out\test\scene5\raw_cam2\img\1687446257
path: C:\Users\javie\Documents\GitHub\Camera2VirtualUCAmI\yolov7\out\test\scene5\cam2\1687446258.png
TIMELINE: 1687446258
I)img# 3 im0s# 360
[[[105 105 105]
  [125 125 125]
  [124 124 124]
  ...
  [225 224 218]
  [225 224 218]
  [225 224 218]]

 [[121 121 121]
  [139 139 139]
  [137 137 137]
  ...
  [225 224 218]
  [225 224 218]
  [225 224 218]]

 [[109 109 109]
  [131 131 131]
  [  0   0   0]
  ...
  [225 224 218]
  [

Nose coordinates: (347.8130340576172, 55.185967683792114)
Foot Left coordinates: (407.14532375335693, 161.9512459039688)
Foot Right coordinates: (397.3446509242058, 164.90707737207413)
[[     407.15      161.95]] prediction  [    0.67454      1.7394]
center (33, 86)
[[     397.34      164.91]] prediction  [    0.67126       1.741]
center (33, 87)
 3D A
 3D B
 	 The image with the result is saved ?: out\test\scene5\raw_cam2\img3D\1687446259_8
 3D C
Saving all!
x1: 605 x2: 640 y1: 269 y2: 360
 	 The image with the result is saved ?: out\test\scene5\raw_cam2\img\1687446259_43_9_chair (1, 360, 640, 3) (91, 35, 3)
Saving all!
x1: 360 x2: 383 y1: 95 y2: 142
 	 The image with the result is saved ?: out\test\scene5\raw_cam2\img\1687446259_43_10_handbag (1, 360, 640, 3) (47, 23, 3)
Saving all!
x1: 125 x2: 163 y1: 81 y2: 133
 	 The image with the result is saved ?: out\test\scene5\raw_cam2\img\1687446259_43_11_chair (1, 360, 640, 3) (52, 38, 3)
Saving all!
x1: 160 x2: 280 y1: 59 y2: 360
 	 The i

Nose coordinates: (391.53907775878906, 113.73699188232422)
Foot Left coordinates: (401.59003353118896, 216.32901203632355)
Foot Right coordinates: (388.6832276582718, 213.11518442630768)
[[     401.59      216.33]] prediction  [    0.85392      1.7999]
center (42, 89)
[[     388.68      213.12]] prediction  [    0.82214      1.7939]
center (41, 89)
 3D A
 3D B
 	 The image with the result is saved ?: out\test\scene5\raw_cam2\img3D\1687446261_4
 3D C
Saving all!
x1: 605 x2: 640 y1: 229 y2: 360
 	 The image with the result is saved ?: out\test\scene5\raw_cam2\img\1687446261_45_5_chair (1, 360, 640, 3) (131, 35, 3)
Saving all!
x1: 372 x2: 420 y1: 121 y2: 155
 	 The image with the result is saved ?: out\test\scene5\raw_cam2\img\1687446261_45_6_laptop (1, 360, 640, 3) (34, 48, 3)
Saving all!
x1: 125 x2: 163 y1: 81 y2: 133
 	 The image with the result is saved ?: out\test\scene5\raw_cam2\img\1687446261_45_7_tv (1, 360, 640, 3) (52, 38, 3)
Saving all!
SHAPES: (360, 640, 3) (360, 640, 3)
 The 

Nose coordinates: (377.10899353027344, 135.82313776016235)
Foot Left coordinates: (394.5665349960327, 217.84873986244202)
Foot Right coordinates: (386.1103501319885, 217.17183113098145)
[[     394.57      217.85]] prediction  [    0.85074      1.8013]
center (42, 90)
[[     386.11      217.17]] prediction  [    0.83579      1.7994]
center (41, 89)
 3D A
 3D B
 	 The image with the result is saved ?: out\test\scene5\raw_cam2\img3D\1687446263_6
 3D C
Saving all!
x1: 81 x2: 120 y1: 117 y2: 154
 	 The image with the result is saved ?: out\test\scene5\raw_cam2\img\1687446263_47_7_handbag (1, 360, 640, 3) (37, 39, 3)
Saving all!
x1: 604 x2: 640 y1: 230 y2: 360
 	 The image with the result is saved ?: out\test\scene5\raw_cam2\img\1687446263_47_8_chair (1, 360, 640, 3) (130, 36, 3)
Saving all!
x1: 125 x2: 163 y1: 81 y2: 133
 	 The image with the result is saved ?: out\test\scene5\raw_cam2\img\1687446263_47_9_chair (1, 360, 640, 3) (52, 38, 3)
Saving all!
x1: 125 x2: 163 y1: 81 y2: 132
 	 The i

 3D C
Saving all!
x1: 126 x2: 163 y1: 81 y2: 133
 	 The image with the result is saved ?: out\test\scene5\raw_cam2\img\1687446265_49_10_chair (1, 360, 640, 3) (52, 37, 3)
Saving all!
x1: 604 x2: 640 y1: 267 y2: 360
 	 The image with the result is saved ?: out\test\scene5\raw_cam2\img\1687446265_49_11_chair (1, 360, 640, 3) (93, 36, 3)
Saving all!
x1: 366 x2: 422 y1: 69 y2: 146
 	 The image with the result is saved ?: out\test\scene5\raw_cam2\img\1687446265_49_12_person (1, 360, 640, 3) (77, 56, 3)
Nose coordinates: (405.1053237915039, 126.40819787979126)
Foot Left coordinates: (399.2094383239746, 239.865375995636)
Foot Right coordinates: (389.02537846565247, 237.4282841682434)
[[     399.21      239.87]] prediction  [    0.96822      1.8384]
center (48, 91)
[[     389.03      237.43]] prediction  [    0.93884      1.8328]
center (46, 91)
 3D A
 3D B
 	 The image with the result is saved ?: out\test\scene5\raw_cam2\img3D\1687446265_12
 3D C
Saving all!
x1: 125 x2: 163 y1: 81 y2: 133
 	 

Nose coordinates: (314.07312393188477, 46.723995208740234)
Foot Left coordinates: (419.7966728210449, 224.76900881528854)
Foot Right coordinates: (403.6347645521164, 230.98382258415222)
[[      419.8      224.77]] prediction  [    0.91891      1.8147]
center (45, 90)
[[     403.63      230.98]] prediction  [    0.92671      1.8231]
center (46, 91)
 3D A
 3D B
 	 The image with the result is saved ?: out\test\scene5\raw_cam2\img3D\1687446267_6
 3D C
Saving all!
x1: 81 x2: 121 y1: 117 y2: 155
 	 The image with the result is saved ?: out\test\scene5\raw_cam2\img\1687446267_51_7_handbag (1, 360, 640, 3) (38, 40, 3)
Saving all!
x1: 364 x2: 427 y1: 67 y2: 136
 	 The image with the result is saved ?: out\test\scene5\raw_cam2\img\1687446267_51_8_person (1, 360, 640, 3) (69, 63, 3)
Box face: [23, 6, 26, 15]
 	 The face with the result is saved ?: out\test\scene5\raw_cam2\faces\1687446267_51_8_person_0 (26, 15, 3)
Nose coordinates: (312.56879806518555, 114.9083662033081)
Foot Left coordinates: (

pred i shape# 0 tensor([[1.25499e+02, 9.32499e+01, 1.63212e+02, 1.45230e+02, 6.79803e-01, 5.60000e+01],
        [3.71159e+02, 1.32456e+02, 4.19128e+02, 1.67337e+02, 6.25872e-01, 6.30000e+01],
        [3.63014e+02, 8.03573e+01, 4.18267e+02, 1.50993e+02, 5.51214e-01, 0.00000e+00],
        [6.04169e+02, 2.41399e+02, 6.39849e+02, 3.76121e+02, 5.25946e-01, 5.60000e+01],
        [3.52943e+01, 1.41698e+02, 7.79526e+01, 1.91610e+02, 3.36837e-01, 2.80000e+01],
        [6.27837e+02, 1.58932e+02, 6.39927e+02, 2.05598e+02, 3.07650e-01, 6.20000e+01],
        [8.05313e+01, 1.28879e+02, 1.21069e+02, 1.65557e+02, 2.92789e-01, 2.60000e+01],
        [8.07408e+01, 1.28846e+02, 1.21030e+02, 1.64515e+02, 2.91909e-01, 2.80000e+01],
        [6.04388e+01, 1.22151e+02, 2.46092e+02, 2.86645e+02, 2.67913e-01, 5.90000e+01]]) (360, 640, 3)
x1: 60 x2: 246 y1: 110 y2: 275
 	 The image with the result is saved ?: out\test\scene5\raw_cam2\img\1687446270_54_1_bed (1, 360, 640, 3) (165, 186, 3)
Saving all!
x1: 81 x2: 12

pred i shape# 0 tensor([[3.64737e+02, 8.03503e+01, 4.20525e+02, 1.47858e+02, 7.74587e-01, 0.00000e+00],
        [3.71927e+02, 1.33146e+02, 4.18118e+02, 1.67883e+02, 7.32842e-01, 6.30000e+01],
        [1.24980e+02, 9.29120e+01, 1.63109e+02, 1.44866e+02, 5.86802e-01, 6.20000e+01],
        [1.25431e+02, 9.32759e+01, 1.63189e+02, 1.45167e+02, 5.19163e-01, 5.60000e+01],
        [6.04055e+02, 2.41029e+02, 6.39790e+02, 3.76103e+02, 4.94425e-01, 5.60000e+01],
        [3.53588e+01, 1.42085e+02, 7.78282e+01, 1.95336e+02, 2.75531e-01, 2.80000e+01],
        [6.28033e+02, 1.58896e+02, 6.39927e+02, 2.05225e+02, 2.73885e-01, 6.20000e+01],
        [3.71556e+02, 1.33408e+02, 4.19803e+02, 1.67481e+02, 2.69084e-01, 2.80000e+01]]) (360, 640, 3)
x1: 372 x2: 420 y1: 121 y2: 155
 	 The image with the result is saved ?: out\test\scene5\raw_cam2\img\1687446273_57_1_suitcase (1, 360, 640, 3) (34, 48, 3)
Saving all!
x1: 628 x2: 640 y1: 147 y2: 193
 	 The image with the result is saved ?: out\test\scene5\raw_cam2

pred i shape# 0 tensor([[1.68089e+02, 5.96820e+01, 2.60177e+02, 3.50205e+02, 9.52718e-01, 0.00000e+00],
        [1.24921e+02, 9.28998e+01, 1.63689e+02, 1.44084e+02, 7.39358e-01, 6.20000e+01],
        [3.72430e+02, 1.34480e+02, 4.19293e+02, 1.67695e+02, 7.08782e-01, 6.30000e+01],
        [6.04903e+02, 2.40746e+02, 6.39850e+02, 3.76316e+02, 4.80060e-01, 5.60000e+01],
        [3.75312e+02, 7.78770e+01, 4.30392e+02, 2.52614e+02, 4.35518e-01, 0.00000e+00],
        [3.71631e+02, 7.95173e+01, 4.21842e+02, 1.53049e+02, 4.06122e-01, 0.00000e+00],
        [2.36921e+02, 1.39120e+02, 2.49309e+02, 1.69312e+02, 4.00136e-01, 3.90000e+01],
        [2.45708e+02, 1.55235e+02, 2.54224e+02, 1.72391e+02, 3.29029e-01, 3.90000e+01],
        [6.27934e+02, 1.58872e+02, 6.39948e+02, 2.05505e+02, 2.74457e-01, 6.20000e+01],
        [8.06247e+01, 1.29409e+02, 1.20745e+02, 1.65421e+02, 2.68779e-01, 2.60000e+01],
        [3.59827e+01, 1.41942e+02, 7.78134e+01, 1.95275e+02, 2.64267e-01, 2.80000e+01]]) (360, 640, 3)
x

pred i shape# 0 tensor([[3.53861e+02, 5.65205e+01, 4.41562e+02, 3.17592e+02, 9.19861e-01, 0.00000e+00],
        [1.25375e+02, 9.33768e+01, 1.62940e+02, 1.45113e+02, 5.42652e-01, 5.60000e+01],
        [1.24870e+02, 9.29505e+01, 1.63222e+02, 1.44983e+02, 4.69208e-01, 6.20000e+01],
        [8.08884e+01, 1.29361e+02, 1.21180e+02, 1.65484e+02, 4.39472e-01, 2.80000e+01],
        [6.05068e+02, 2.41781e+02, 6.39929e+02, 3.75865e+02, 3.82000e-01, 5.60000e+01],
        [3.54277e+01, 1.42122e+02, 7.76863e+01, 1.90081e+02, 3.59682e-01, 2.80000e+01],
        [6.27980e+02, 1.58890e+02, 6.39936e+02, 2.05548e+02, 3.51291e-01, 6.20000e+01],
        [8.07157e+01, 1.29493e+02, 1.16124e+02, 1.67513e+02, 2.78145e-01, 2.60000e+01]]) (360, 640, 3)
x1: 81 x2: 116 y1: 117 y2: 156
 	 The image with the result is saved ?: out\test\scene5\raw_cam2\img\1687446277_61_1_handbag (1, 360, 640, 3) (39, 35, 3)
Saving all!
x1: 628 x2: 640 y1: 147 y2: 194
 	 The image with the result is saved ?: out\test\scene5\raw_cam2\i

Nose coordinates: (439.6471405029297, 135.34503936767578)
Foot Left coordinates: (391.98160767555237, 216.41502475738525)
Foot Right coordinates: (382.37065148353577, 215.9540662765503)
[[     391.98      216.42]] prediction  [    0.84081      1.7989]
center (42, 89)
[[     382.37      215.95]] prediction  [    0.82525      1.7972]
center (41, 89)
 3D A
 3D B
 	 The image with the result is saved ?: out\test\scene5\raw_cam2\img3D\1687446279_7
 3D C
Saving all!
x1: 386 x2: 486 y1: 43 y2: 289
 	 The image with the result is saved ?: out\test\scene5\raw_cam2\img\1687446279_63_8_person (1, 360, 640, 3) (246, 100, 3)
Box face: [2, 34, 27, 17]
 	 The face with the result is saved ?: out\test\scene5\raw_cam2\faces\1687446279_63_8_person_0 (27, 17, 3)
Nose coordinates: (424.95582580566406, 47.23618984222412)
Foot Left coordinates: (391.1494240760803, 249.62090265750885)
Foot Right coordinates: (432.66417837142944, 258.29063045978546)
[[     391.15      249.62]] prediction  [     1.0142      1.

Nose coordinates: (449.2360305786133, 49.724518060684204)
Foot Left coordinates: (398.5666602253914, 256.95330142974854)
Foot Right coordinates: (433.500123500824, 256.3815402984619)
[[     398.57      256.95]] prediction  [     1.0758      1.8742]
center (53, 93)
[[      433.5      256.38]] prediction  [     1.1293      1.8766]
center (56, 93)
 3D A
 3D B
 	 The image with the result is saved ?: out\test\scene5\raw_cam2\img3D\1687446281_8
 3D C
Saving all!
SHAPES: (360, 640, 3) (360, 640, 3)
 The image with the result is saved ?: out\test\scene5\raw_cam2\img\1687446281
path: C:\Users\javie\Documents\GitHub\Camera2VirtualUCAmI\yolov7\out\test\scene5\cam2\1687446282.png
TIMELINE: 1687446282
I)img# 3 im0s# 360
[[[105 105 105]
  [125 125 125]
  [124 124 124]
  ...
  [226 225 219]
  [226 225 219]
  [226 225 219]]

 [[121 121 121]
  [139 139 139]
  [137 137 137]
  ...
  [226 225 219]
  [226 225 219]
  [226 225 219]]

 [[109 109 109]
  [131 131 131]
  [  0   0   0]
  ...
  [226 225 219]
  [2

Nose coordinates: (409.4293212890625, 50.55791258811951)
Foot Left coordinates: (402.8811652958393, 260.3072637319565)
Foot Right coordinates: (422.77406960725784, 249.8844347000122)
[[     402.88      260.31]] prediction  [     1.1074      1.8827]
center (55, 94)
[[     422.77      249.88]] prediction  [     1.0669      1.8611]
center (53, 93)
 3D A
 3D B
 	 The image with the result is saved ?: out\test\scene5\raw_cam2\img3D\1687446284_7
 3D C
Saving all!
SHAPES: (360, 640, 3) (360, 640, 3)
 The image with the result is saved ?: out\test\scene5\raw_cam2\img\1687446284
path: C:\Users\javie\Documents\GitHub\Camera2VirtualUCAmI\yolov7\out\test\scene5\cam2\1687446285.png
TIMELINE: 1687446285
I)img# 3 im0s# 360
[[[105 105 105]
  [125 125 125]
  [124 124 124]
  ...
  [228 224 220]
  [228 224 220]
  [228 224 220]]

 [[121 121 121]
  [139 139 139]
  [137 137 137]
  ...
  [228 224 220]
  [228 224 220]
  [228 224 220]]

 [[109 109 109]
  [131 131 131]
  [  0   0   0]
  ...
  [228 224 220]
  [2

pred i shape# 0 tensor([[3.82484e+02, 6.01919e+01, 4.75202e+02, 3.08692e+02, 9.52090e-01, 0.00000e+00],
        [1.25492e+02, 9.33698e+01, 1.63027e+02, 1.45135e+02, 7.05849e-01, 5.60000e+01],
        [6.04448e+02, 2.80086e+02, 6.40045e+02, 3.76985e+02, 5.66938e-01, 5.60000e+01],
        [8.08642e+01, 1.29287e+02, 1.21169e+02, 1.64974e+02, 5.11375e-01, 2.80000e+01],
        [8.06979e+01, 1.29149e+02, 1.19602e+02, 1.66641e+02, 3.86063e-01, 2.60000e+01],
        [3.78485e+02, 8.07398e+01, 4.17271e+02, 1.37063e+02, 3.68276e-01, 0.00000e+00],
        [6.22338e+01, 1.24646e+02, 2.45842e+02, 2.88258e+02, 3.14572e-01, 6.00000e+01],
        [6.28016e+02, 1.58978e+02, 6.39927e+02, 2.05968e+02, 2.83740e-01, 6.20000e+01],
        [3.54408e+01, 1.42273e+02, 7.77625e+01, 1.95161e+02, 2.83010e-01, 2.80000e+01]]) (360, 640, 3)
x1: 35 x2: 78 y1: 130 y2: 183
 	 The image with the result is saved ?: out\test\scene5\raw_cam2\img\1687446287_71_1_suitcase (1, 360, 640, 3) (53, 43, 3)
Saving all!
x1: 628 x2:

pred i shape# 0 tensor([[2.45499e+02, 4.29057e+01, 3.18401e+02, 2.61909e+02, 9.57819e-01, 0.00000e+00],
        [3.67429e+02, 8.03546e+01, 4.23590e+02, 1.47764e+02, 8.12594e-01, 0.00000e+00],
        [1.25505e+02, 9.33639e+01, 1.63133e+02, 1.45149e+02, 7.04945e-01, 5.60000e+01],
        [3.71930e+02, 1.32332e+02, 4.19248e+02, 1.68452e+02, 6.98025e-01, 6.30000e+01],
        [6.04271e+02, 2.41233e+02, 6.39778e+02, 3.76803e+02, 5.03883e-01, 5.60000e+01],
        [6.02700e+01, 1.23943e+02, 2.46474e+02, 2.86592e+02, 3.94676e-01, 5.90000e+01],
        [1.25008e+02, 9.29383e+01, 1.63154e+02, 1.45031e+02, 3.63005e-01, 6.20000e+01],
        [3.58284e+01, 1.42169e+02, 7.77896e+01, 1.90395e+02, 3.40747e-01, 2.80000e+01],
        [4.69832e+02, 1.37151e+02, 4.82158e+02, 1.62061e+02, 3.31955e-01, 3.90000e+01],
        [6.27994e+02, 1.59070e+02, 6.39930e+02, 2.05479e+02, 3.31391e-01, 6.20000e+01],
        [3.57712e+01, 1.42175e+02, 7.78364e+01, 1.89574e+02, 2.78298e-01, 2.40000e+01],
        [9.21833

[[      403.9       255.2]] prediction  [     1.0724      1.8708]
center (53, 93)
[[      389.2      254.73]] prediction  [     1.0447      1.8681]
center (52, 93)
 3D A
 3D B
 	 The image with the result is saved ?: out\test\scene5\raw_cam2\img3D\1687446290_11
 3D C
Saving all!
x1: 372 x2: 423 y1: 122 y2: 156
 	 The image with the result is saved ?: out\test\scene5\raw_cam2\img\1687446290_74_12_laptop (1, 360, 640, 3) (34, 51, 3)
Saving all!
x1: 268 x2: 310 y1: 24 y2: 229
 	 The image with the result is saved ?: out\test\scene5\raw_cam2\img\1687446290_74_13_person (1, 360, 640, 3) (205, 42, 3)
Nose coordinates: (599.5259475708008, 57.259132862091064)
Foot Left coordinates: (304.6351041793823, 208.21877592802048)
Foot Right coordinates: (297.99680638313293, 219.01574754714966)
[[     304.64      208.22]] prediction  [    0.68389      1.7775]
center (34, 88)
[[        298      219.02]] prediction  [     0.7135      1.7918]
center (35, 89)
 3D A
 3D B
 	 The image with the result is save

Nose coordinates: (318.3894157409668, 61.582242250442505)
Foot Left coordinates: (411.1504031419754, 225.7278790473938)
Foot Right coordinates: (395.32308784127235, 232.40269374847412)
[[     411.15      225.73]] prediction  [    0.91121      1.8152]
center (45, 90)
[[     395.32       232.4]] prediction  [    0.92164      1.8246]
center (46, 91)
 3D A
 3D B
 	 The image with the result is saved ?: out\test\scene5\raw_cam2\img3D\1687446292_10
 3D C
Saving all!
x1: 372 x2: 418 y1: 121 y2: 156
 	 The image with the result is saved ?: out\test\scene5\raw_cam2\img\1687446292_76_11_laptop (1, 360, 640, 3) (35, 46, 3)
Saving all!
x1: 288 x2: 343 y1: 23 y2: 236
 	 The image with the result is saved ?: out\test\scene5\raw_cam2\img\1687446292_76_12_person (1, 360, 640, 3) (213, 55, 3)
Nose coordinates: (541.8645858764648, 58.46106290817261)
Foot Left coordinates: (304.0805658996105, 164.4324643611908)
Foot Right coordinates: (305.10441917181015, 194.7819646000862)
[[     304.08      164.43]] pr

Nose coordinates: (221.40466690063477, 41.12679362297058)
Foot Left coordinates: (410.1192318201065, 149.56994724273682)
Foot Right coordinates: (393.9691382050514, 147.86488091945648)
[[     410.12      149.57]] prediction  [    0.64624      1.7294]
center (32, 86)
[[     393.97      147.86]] prediction  [    0.62454      1.7264]
center (31, 86)
 3D A
 3D B
 	 The image with the result is saved ?: out\test\scene5\raw_cam2\img3D\1687446294_10
 3D C
Saving all!
x1: 125 x2: 163 y1: 81 y2: 133
 	 The image with the result is saved ?: out\test\scene5\raw_cam2\img\1687446294_78_11_chair (1, 360, 640, 3) (52, 38, 3)
Saving all!
x1: 288 x2: 337 y1: 22 y2: 237
 	 The image with the result is saved ?: out\test\scene5\raw_cam2\img\1687446294_78_12_person (1, 360, 640, 3) (215, 49, 3)
Nose coordinates: (562.944221496582, 57.472341656684875)
Foot Left coordinates: (304.2884963452816, 162.01975059509277)
Foot Right coordinates: (303.13288286328316, 169.012856900692)
[[     304.29      162.02]] pred

Nose coordinates: (255.69583892822266, 44.885244369506836)
Foot Left coordinates: (421.7152451276779, 227.2628219127655)
Foot Right coordinates: (393.88427433371544, 231.81367009878159)
[[     421.72      227.26]] prediction  [    0.93411      1.8189]
center (46, 90)
[[     393.88      231.81]] prediction  [    0.91643      1.8234]
center (45, 91)
 3D A
 3D B
 	 The image with the result is saved ?: out\test\scene5\raw_cam2\img3D\1687446296_9
 3D C
Saving all!
x1: 287 x2: 356 y1: 21 y2: 237
 	 The image with the result is saved ?: out\test\scene5\raw_cam2\img\1687446296_80_10_person (1, 360, 640, 3) (216, 69, 3)
Box face: [30, 10, 35, 19]
 	 The face with the result is saved ?: out\test\scene5\raw_cam2\faces\1687446296_80_10_person_0 (35, 19, 3)
Nose coordinates: (424.59529876708984, 55.9019672870636)
Foot Left coordinates: (302.21269296109676, 163.60473203659058)
Foot Right coordinates: (302.64190880954266, 209.74537897109985)
[[     302.21       163.6]] prediction  [    0.55528      

Nose coordinates: (534.0382385253906, 54.39635217189789)
Foot Left coordinates: (310.46793991327286, 159.66397500038147)
Foot Right coordinates: (302.8815606236458, 172.078120470047)
[[     310.47      159.66]] prediction  [    0.55633      1.7271]
center (27, 86)
[[     302.88      172.08]] prediction  [     0.5761      1.7372]
center (28, 86)
 3D A
 3D B
 	 The image with the result is saved ?: out\test\scene5\raw_cam2\img3D\1687446298_10
 3D C
Saving all!
SHAPES: (360, 640, 3) (360, 640, 3)
 The image with the result is saved ?: out\test\scene5\raw_cam2\img\1687446298
path: C:\Users\javie\Documents\GitHub\Camera2VirtualUCAmI\yolov7\out\test\scene5\cam2\1687446299.png
TIMELINE: 1687446299
I)img# 3 im0s# 360
[[[105 105 105]
  [125 125 125]
  [124 124 124]
  ...
  [226 225 219]
  [226 225 219]
  [226 225 219]]

 [[121 121 121]
  [139 139 139]
  [137 137 137]
  ...
  [226 225 219]
  [226 225 219]
  [226 225 219]]

 [[109 109 109]
  [131 131 131]
  [  0   0   0]
  ...
  [226 225 219]
  [

Nose coordinates: (408.57444763183594, 126.75724983215332)
Foot Left coordinates: (399.8498704433441, 223.98946380615234)
Foot Right coordinates: (387.3598435521126, 220.92929649353027)
[[     399.85      223.99]] prediction  [    0.88647      1.8112]
center (44, 90)
[[     387.36      220.93]] prediction  [    0.85424      1.8051]
center (42, 90)
 3D A
 3D B
 	 The image with the result is saved ?: out\test\scene5\raw_cam2\img3D\1687446300_10
 3D C
Saving all!
x1: 259 x2: 311 y1: 24 y2: 215
 	 The image with the result is saved ?: out\test\scene5\raw_cam2\img\1687446300_84_11_person (1, 360, 640, 3) (191, 52, 3)
Nose coordinates: (517.2888946533203, 56.34512186050415)
Foot Left coordinates: (307.1718611717224, 201.73173314332962)
Foot Right coordinates: (281.45399713516235, 200.2917207479477)
[[     307.17      201.73]] prediction  [    0.66567      1.7695]
center (33, 88)
[[     281.45      200.29]] prediction  [    0.62467      1.7647]
center (31, 88)
 3D A
 3D B
 	 The image with t

Box face: [28, 8, 27, 19]
 	 The face with the result is saved ?: out\test\scene5\raw_cam2\faces\1687446302_86_13_person_0 (27, 19, 3)
Nose coordinates: (495.1730728149414, 59.08597469329834)
Foot Left coordinates: (305.19026470184326, 186.06508988142014)
Foot Right coordinates: (273.4620668888092, 186.13647770881653)
[[     305.19      186.07]] prediction  [    0.61566      1.7514]
center (30, 87)
[[     273.46      186.14]] prediction  [    0.57344      1.7478]
center (28, 87)
 3D A
 3D B
 	 The image with the result is saved ?: out\test\scene5\raw_cam2\img3D\1687446302_13
 3D C
Saving all!
SHAPES: (360, 640, 3) (360, 640, 3)
 The image with the result is saved ?: out\test\scene5\raw_cam2\img\1687446302
path: C:\Users\javie\Documents\GitHub\Camera2VirtualUCAmI\yolov7\out\test\scene5\cam2\1687446303.png
TIMELINE: 1687446303
I)img# 3 im0s# 360
[[[105 105 105]
  [125 125 125]
  [124 124 124]
  ...
  [226 225 219]
  [226 225 219]
  [226 225 219]]

 [[121 121 121]
  [139 139 139]
  [137 1

Saving all!
x1: 255 x2: 309 y1: 16 y2: 194
 	 The image with the result is saved ?: out\test\scene5\raw_cam2\img\1687446304_88_12_person (1, 360, 640, 3) (178, 54, 3)
Box face: [19, 8, 26, 19]
 	 The face with the result is saved ?: out\test\scene5\raw_cam2\faces\1687446304_88_12_person_0 (26, 19, 3)
Nose coordinates: (410.01365661621094, 58.552268743515015)
Foot Left coordinates: (303.26345014572144, 187.4624434709549)
Foot Right coordinates: (277.3341085910797, 186.00000190734863)
[[     303.26      187.46]] prediction  [    0.61702      1.7527]
center (30, 87)
[[     277.33         186]] prediction  [     0.5783      1.7481]
center (28, 87)
 3D A
 3D B
 	 The image with the result is saved ?: out\test\scene5\raw_cam2\img3D\1687446304_12
 3D C
Saving all!
SHAPES: (360, 640, 3) (360, 640, 3)
 The image with the result is saved ?: out\test\scene5\raw_cam2\img\1687446304
path: C:\Users\javie\Documents\GitHub\Camera2VirtualUCAmI\yolov7\out\test\scene5\cam2\1687446305.png
TIMELINE: 168744

Nose coordinates: (458.46614837646484, 59.968249797821045)
Foot Left coordinates: (300.74150943756104, 188.69687378406525)
Foot Right coordinates: (278.1552023887634, 186.0836844444275)
[[     300.74       188.7]] prediction  [    0.61714      1.7537]
center (30, 87)
[[     278.16      186.08]] prediction  [    0.57963      1.7483]
center (28, 87)
 3D A
 3D B
 	 The image with the result is saved ?: out\test\scene5\raw_cam2\img3D\1687446306_8
 3D C
Saving all!
SHAPES: (360, 640, 3) (360, 640, 3)
 The image with the result is saved ?: out\test\scene5\raw_cam2\img\1687446306
path: C:\Users\javie\Documents\GitHub\Camera2VirtualUCAmI\yolov7\out\test\scene5\cam2\1687446307.png
TIMELINE: 1687446307
I)img# 3 im0s# 360
[[[105 105 105]
  [125 125 125]
  [124 124 124]
  ...
  [228 225 219]
  [228 225 219]
  [228 225 219]]

 [[121 121 121]
  [139 139 139]
  [137 137 137]
  ...
  [228 225 219]
  [228 225 219]
  [228 225 219]]

 [[109 109 109]
  [131 131 131]
  [  0   0   0]
  ...
  [228 225 219]
 

Nose coordinates: (482.3851776123047, 54.438854455947876)
Foot Left coordinates: (315.4333609342575, 238.1948642730713)
Foot Right coordinates: (290.962691873312, 242.89612007141113)
[[     315.43      238.19]] prediction  [    0.82526      1.8257]
center (41, 91)
[[     290.96       242.9]] prediction  [    0.80751      1.8317]
center (40, 91)
 3D A
 3D B
 	 The image with the result is saved ?: out\test\scene5\raw_cam2\img3D\1687446309_7
 3D C
Saving all!
SHAPES: (360, 640, 3) (360, 640, 3)
 The image with the result is saved ?: out\test\scene5\raw_cam2\img\1687446309
Done
